// flow-typed signature: 6446b146a47f01b5ada99c97f724432b
// flow-typed version: <<STUB>>/apollo-errors_v1.5.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-errors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-errors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-errors/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-errors/dist/index.js' {
  declare module.exports: $Exports<'apollo-errors/dist/index'>;
}
