// flow-typed signature: b89f3b195241b01e4c62136cf0dcd360
// flow-typed version: <<STUB>>/bulma_v0.6.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bulma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bulma' {
  declare module.exports: any;
}
