// flow-typed signature: 4994d48e16e44ec4ccb6c963a9c146c7
// flow-typed version: <<STUB>>/connect-wwwhisper_v0.1.19/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connect-wwwhisper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'connect-wwwhisper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'connect-wwwhisper/bug' {
  declare module.exports: any;
}

declare module 'connect-wwwhisper/Gruntfile' {
  declare module.exports: any;
}

declare module 'connect-wwwhisper/lib/connect-wwwhisper' {
  declare module.exports: any;
}

declare module 'connect-wwwhisper/test/connect-wwwhisper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'connect-wwwhisper/bug.js' {
  declare module.exports: $Exports<'connect-wwwhisper/bug'>;
}
declare module 'connect-wwwhisper/Gruntfile.js' {
  declare module.exports: $Exports<'connect-wwwhisper/Gruntfile'>;
}
declare module 'connect-wwwhisper/lib/connect-wwwhisper.js' {
  declare module.exports: $Exports<'connect-wwwhisper/lib/connect-wwwhisper'>;
}
declare module 'connect-wwwhisper/test/connect-wwwhisper.js' {
  declare module.exports: $Exports<'connect-wwwhisper/test/connect-wwwhisper'>;
}
