// flow-typed signature: 49630b4914a9c08e5cbbc5bd83c0e56a
// flow-typed version: <<STUB>>/crypto_v1.0.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'crypto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'crypto' {
  declare module.exports: any;
}
