// flow-typed signature: 58977c2d24bab35119c7c49d8a913a17
// flow-typed version: <<STUB>>/evaporate_v2.1.4/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'evaporate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'evaporate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'evaporate/evaporate' {
  declare module.exports: any;
}

declare module 'evaporate/example/awsv4_signing_example' {
  declare module.exports: any;
}

declare module 'evaporate/example/electron/main' {
  declare module.exports: any;
}

declare module 'evaporate/example/electron/renderer' {
  declare module.exports: any;
}

declare module 'evaporate/example/signing_example_express_response_handler' {
  declare module.exports: any;
}

declare module 'evaporate/example/signing_example_express' {
  declare module.exports: any;
}

declare module 'evaporate/example/signing_example_lambda_response_handler' {
  declare module.exports: any;
}

declare module 'evaporate/example/signing_example_lambda' {
  declare module.exports: any;
}

declare module 'evaporate/example/SigningExample-awsv4' {
  declare module.exports: any;
}

declare module 'evaporate/example/SigningExample' {
  declare module.exports: any;
}

declare module 'evaporate/test/auth.spec' {
  declare module.exports: any;
}

declare module 'evaporate/test/aws_config.spec' {
  declare module.exports: any;
}

declare module 'evaporate/test/cached-parts.spec' {
  declare module.exports: any;
}

declare module 'evaporate/test/cancel-abort.spec' {
  declare module.exports: any;
}

declare module 'evaporate/test/common-case.spec' {
  declare module.exports: any;
}

declare module 'evaporate/test/evaporate.spec' {
  declare module.exports: any;
}

declare module 'evaporate/test/fixtures/complete-response' {
  declare module.exports: any;
}

declare module 'evaporate/test/fixtures/get-parts-truncated-response' {
  declare module.exports: any;
}

declare module 'evaporate/test/fixtures/init-response' {
  declare module.exports: any;
}

declare module 'evaporate/test/helpers/browser-env' {
  declare module.exports: any;
}

declare module 'evaporate/test/pause-resume.spec' {
  declare module.exports: any;
}

declare module 'evaporate/test/s3-object-reuse.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'evaporate/evaporate.js' {
  declare module.exports: $Exports<'evaporate/evaporate'>;
}
declare module 'evaporate/example/awsv4_signing_example.js' {
  declare module.exports: $Exports<'evaporate/example/awsv4_signing_example'>;
}
declare module 'evaporate/example/electron/main.js' {
  declare module.exports: $Exports<'evaporate/example/electron/main'>;
}
declare module 'evaporate/example/electron/renderer.js' {
  declare module.exports: $Exports<'evaporate/example/electron/renderer'>;
}
declare module 'evaporate/example/signing_example_express_response_handler.js' {
  declare module.exports: $Exports<'evaporate/example/signing_example_express_response_handler'>;
}
declare module 'evaporate/example/signing_example_express.js' {
  declare module.exports: $Exports<'evaporate/example/signing_example_express'>;
}
declare module 'evaporate/example/signing_example_lambda_response_handler.js' {
  declare module.exports: $Exports<'evaporate/example/signing_example_lambda_response_handler'>;
}
declare module 'evaporate/example/signing_example_lambda.js' {
  declare module.exports: $Exports<'evaporate/example/signing_example_lambda'>;
}
declare module 'evaporate/example/SigningExample-awsv4.js' {
  declare module.exports: $Exports<'evaporate/example/SigningExample-awsv4'>;
}
declare module 'evaporate/example/SigningExample.js' {
  declare module.exports: $Exports<'evaporate/example/SigningExample'>;
}
declare module 'evaporate/test/auth.spec.js' {
  declare module.exports: $Exports<'evaporate/test/auth.spec'>;
}
declare module 'evaporate/test/aws_config.spec.js' {
  declare module.exports: $Exports<'evaporate/test/aws_config.spec'>;
}
declare module 'evaporate/test/cached-parts.spec.js' {
  declare module.exports: $Exports<'evaporate/test/cached-parts.spec'>;
}
declare module 'evaporate/test/cancel-abort.spec.js' {
  declare module.exports: $Exports<'evaporate/test/cancel-abort.spec'>;
}
declare module 'evaporate/test/common-case.spec.js' {
  declare module.exports: $Exports<'evaporate/test/common-case.spec'>;
}
declare module 'evaporate/test/evaporate.spec.js' {
  declare module.exports: $Exports<'evaporate/test/evaporate.spec'>;
}
declare module 'evaporate/test/fixtures/complete-response.js' {
  declare module.exports: $Exports<'evaporate/test/fixtures/complete-response'>;
}
declare module 'evaporate/test/fixtures/get-parts-truncated-response.js' {
  declare module.exports: $Exports<'evaporate/test/fixtures/get-parts-truncated-response'>;
}
declare module 'evaporate/test/fixtures/init-response.js' {
  declare module.exports: $Exports<'evaporate/test/fixtures/init-response'>;
}
declare module 'evaporate/test/helpers/browser-env.js' {
  declare module.exports: $Exports<'evaporate/test/helpers/browser-env'>;
}
declare module 'evaporate/test/pause-resume.spec.js' {
  declare module.exports: $Exports<'evaporate/test/pause-resume.spec'>;
}
declare module 'evaporate/test/s3-object-reuse.spec.js' {
  declare module.exports: $Exports<'evaporate/test/s3-object-reuse.spec'>;
}
