// flow-typed signature: a26a9959531622ef0ac556e20baa6b58
// flow-typed version: <<STUB>>/express-sslify_v1.2.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-sslify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-sslify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-sslify/Gruntfile' {
  declare module.exports: any;
}

declare module 'express-sslify/test/express-sslify.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-sslify/Gruntfile.js' {
  declare module.exports: $Exports<'express-sslify/Gruntfile'>;
}
declare module 'express-sslify/index' {
  declare module.exports: $Exports<'express-sslify'>;
}
declare module 'express-sslify/index.js' {
  declare module.exports: $Exports<'express-sslify'>;
}
declare module 'express-sslify/test/express-sslify.test.js' {
  declare module.exports: $Exports<'express-sslify/test/express-sslify.test'>;
}
