// flow-typed signature: 177f3320d3cbe6cd04dbe2685d091d25
// flow-typed version: <<STUB>>/graphql-apollo-errors_v2.0.3/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-apollo-errors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-apollo-errors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-apollo-errors/dist/index' {
  declare module.exports: any;
}

declare module 'graphql-apollo-errors/dist/index.spec' {
  declare module.exports: any;
}

declare module 'graphql-apollo-errors/wallaby' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-apollo-errors/dist/index.js' {
  declare module.exports: $Exports<'graphql-apollo-errors/dist/index'>;
}
declare module 'graphql-apollo-errors/dist/index.spec.js' {
  declare module.exports: $Exports<'graphql-apollo-errors/dist/index.spec'>;
}
declare module 'graphql-apollo-errors/wallaby.js' {
  declare module.exports: $Exports<'graphql-apollo-errors/wallaby'>;
}
