// flow-typed signature: 572e3ca260915d0867b4b89afcc87969
// flow-typed version: <<STUB>>/hard-source-webpack-plugin_v0.7.0-alpha.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hard-source-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hard-source-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hard-source-webpack-plugin/lib/archetype-system' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/asset-cache' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/cache-serializer-factory' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/default-config-hash' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/devtool-options' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/enhanced-resolve-cache' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/env-hash' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-asset-plugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-basic-dependency-plugin-legacy' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-basic-dependency-plugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-compilation-plugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-concatenation-module-plugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-dependency-block-plugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-generator-plugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-module-assets-plugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-module-errors-plugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-module-extract-text-plugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-module-mini-css-extract-plugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-normal-module-factory-plugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-normal-module-plugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-parser-plugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-source-append-serializer-plugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-source-append-serializer' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-source-file-serializer-plugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-source-file-serializer' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-source-json-serializer-plugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-source-json-serializer' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-source-leveldb-serializer-plugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-source-leveldb-serializer' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/hard-source-source-plugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/logger-factory' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/md5-cache' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/module-cache' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/module-resolver-cache' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/schema-4/_generate' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/schema-4/index' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/util/bulk-fs-task' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/util/index' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/util/log-messages' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/util/Object.entries' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/util/Object.values' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/util/plugin-compat' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/util/promisify' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/util/relate-context' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/util/serial' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hard-source-webpack-plugin/index' {
  declare module.exports: $Exports<'hard-source-webpack-plugin'>;
}
declare module 'hard-source-webpack-plugin/index.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin'>;
}
declare module 'hard-source-webpack-plugin/lib/archetype-system.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/archetype-system'>;
}
declare module 'hard-source-webpack-plugin/lib/asset-cache.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/asset-cache'>;
}
declare module 'hard-source-webpack-plugin/lib/cache-serializer-factory.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/cache-serializer-factory'>;
}
declare module 'hard-source-webpack-plugin/lib/default-config-hash.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/default-config-hash'>;
}
declare module 'hard-source-webpack-plugin/lib/devtool-options.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/devtool-options'>;
}
declare module 'hard-source-webpack-plugin/lib/enhanced-resolve-cache.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/enhanced-resolve-cache'>;
}
declare module 'hard-source-webpack-plugin/lib/env-hash.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/env-hash'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-asset-plugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-asset-plugin'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-basic-dependency-plugin-legacy.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-basic-dependency-plugin-legacy'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-basic-dependency-plugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-basic-dependency-plugin'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-compilation-plugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-compilation-plugin'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-concatenation-module-plugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-concatenation-module-plugin'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-dependency-block-plugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-dependency-block-plugin'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-generator-plugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-generator-plugin'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-module-assets-plugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-module-assets-plugin'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-module-errors-plugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-module-errors-plugin'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-module-extract-text-plugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-module-extract-text-plugin'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-module-mini-css-extract-plugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-module-mini-css-extract-plugin'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-normal-module-factory-plugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-normal-module-factory-plugin'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-normal-module-plugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-normal-module-plugin'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-parser-plugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-parser-plugin'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-source-append-serializer-plugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-source-append-serializer-plugin'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-source-append-serializer.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-source-append-serializer'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-source-file-serializer-plugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-source-file-serializer-plugin'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-source-file-serializer.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-source-file-serializer'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-source-json-serializer-plugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-source-json-serializer-plugin'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-source-json-serializer.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-source-json-serializer'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-source-leveldb-serializer-plugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-source-leveldb-serializer-plugin'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-source-leveldb-serializer.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-source-leveldb-serializer'>;
}
declare module 'hard-source-webpack-plugin/lib/hard-source-source-plugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/hard-source-source-plugin'>;
}
declare module 'hard-source-webpack-plugin/lib/logger-factory.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/logger-factory'>;
}
declare module 'hard-source-webpack-plugin/lib/md5-cache.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/md5-cache'>;
}
declare module 'hard-source-webpack-plugin/lib/module-cache.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/module-cache'>;
}
declare module 'hard-source-webpack-plugin/lib/module-resolver-cache.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/module-resolver-cache'>;
}
declare module 'hard-source-webpack-plugin/lib/schema-4/_generate.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/schema-4/_generate'>;
}
declare module 'hard-source-webpack-plugin/lib/schema-4/index.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/schema-4/index'>;
}
declare module 'hard-source-webpack-plugin/lib/util/bulk-fs-task.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/util/bulk-fs-task'>;
}
declare module 'hard-source-webpack-plugin/lib/util/index.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/util/index'>;
}
declare module 'hard-source-webpack-plugin/lib/util/log-messages.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/util/log-messages'>;
}
declare module 'hard-source-webpack-plugin/lib/util/Object.entries.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/util/Object.entries'>;
}
declare module 'hard-source-webpack-plugin/lib/util/Object.values.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/util/Object.values'>;
}
declare module 'hard-source-webpack-plugin/lib/util/plugin-compat.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/util/plugin-compat'>;
}
declare module 'hard-source-webpack-plugin/lib/util/promisify.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/util/promisify'>;
}
declare module 'hard-source-webpack-plugin/lib/util/relate-context.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/util/relate-context'>;
}
declare module 'hard-source-webpack-plugin/lib/util/serial.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/util/serial'>;
}
