// flow-typed signature: 2ae641211e5908ede94904cb40232645
// flow-typed version: <<STUB>>/images-upload-middleware_v^1.1.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'images-upload-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'images-upload-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'images-upload-middleware/lib/index' {
  declare module.exports: any;
}

declare module 'images-upload-middleware/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'images-upload-middleware/lib/index.js' {
  declare module.exports: $Exports<'images-upload-middleware/lib/index'>;
}
declare module 'images-upload-middleware/src/index.js' {
  declare module.exports: $Exports<'images-upload-middleware/src/index'>;
}
