// flow-typed signature: 3ff7cdcdf3f5cdb9b17600167ab4f3cc
// flow-typed version: <<STUB>>/jake_vlatest/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jake'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jake' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jake/bin/cli' {
  declare module.exports: any;
}

declare module 'jake/lib/api' {
  declare module.exports: any;
}

declare module 'jake/lib/jake' {
  declare module.exports: any;
}

declare module 'jake/lib/loader' {
  declare module.exports: any;
}

declare module 'jake/lib/namespace' {
  declare module.exports: any;
}

declare module 'jake/lib/package_task' {
  declare module.exports: any;
}

declare module 'jake/lib/parseargs' {
  declare module.exports: any;
}

declare module 'jake/lib/program' {
  declare module.exports: any;
}

declare module 'jake/lib/publish_task' {
  declare module.exports: any;
}

declare module 'jake/lib/rule' {
  declare module.exports: any;
}

declare module 'jake/lib/task/directory_task' {
  declare module.exports: any;
}

declare module 'jake/lib/task/file_task' {
  declare module.exports: any;
}

declare module 'jake/lib/task/index' {
  declare module.exports: any;
}

declare module 'jake/lib/task/task' {
  declare module.exports: any;
}

declare module 'jake/lib/test_task' {
  declare module.exports: any;
}

declare module 'jake/lib/utils/index' {
  declare module.exports: any;
}

declare module 'jake/lib/utils/logger' {
  declare module.exports: any;
}

declare module 'jake/lib/watch_task' {
  declare module.exports: any;
}

declare module 'jake/test/concurrent' {
  declare module.exports: any;
}

declare module 'jake/test/exec' {
  declare module.exports: any;
}

declare module 'jake/test/file_task' {
  declare module.exports: any;
}

declare module 'jake/test/helpers' {
  declare module.exports: any;
}

declare module 'jake/test/namespace' {
  declare module.exports: any;
}

declare module 'jake/test/parseargs' {
  declare module.exports: any;
}

declare module 'jake/test/publish_task' {
  declare module.exports: any;
}

declare module 'jake/test/rule' {
  declare module.exports: any;
}

declare module 'jake/test/selfdep' {
  declare module.exports: any;
}

declare module 'jake/test/task_base' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jake/bin/cli.js' {
  declare module.exports: $Exports<'jake/bin/cli'>;
}
declare module 'jake/lib/api.js' {
  declare module.exports: $Exports<'jake/lib/api'>;
}
declare module 'jake/lib/jake.js' {
  declare module.exports: $Exports<'jake/lib/jake'>;
}
declare module 'jake/lib/loader.js' {
  declare module.exports: $Exports<'jake/lib/loader'>;
}
declare module 'jake/lib/namespace.js' {
  declare module.exports: $Exports<'jake/lib/namespace'>;
}
declare module 'jake/lib/package_task.js' {
  declare module.exports: $Exports<'jake/lib/package_task'>;
}
declare module 'jake/lib/parseargs.js' {
  declare module.exports: $Exports<'jake/lib/parseargs'>;
}
declare module 'jake/lib/program.js' {
  declare module.exports: $Exports<'jake/lib/program'>;
}
declare module 'jake/lib/publish_task.js' {
  declare module.exports: $Exports<'jake/lib/publish_task'>;
}
declare module 'jake/lib/rule.js' {
  declare module.exports: $Exports<'jake/lib/rule'>;
}
declare module 'jake/lib/task/directory_task.js' {
  declare module.exports: $Exports<'jake/lib/task/directory_task'>;
}
declare module 'jake/lib/task/file_task.js' {
  declare module.exports: $Exports<'jake/lib/task/file_task'>;
}
declare module 'jake/lib/task/index.js' {
  declare module.exports: $Exports<'jake/lib/task/index'>;
}
declare module 'jake/lib/task/task.js' {
  declare module.exports: $Exports<'jake/lib/task/task'>;
}
declare module 'jake/lib/test_task.js' {
  declare module.exports: $Exports<'jake/lib/test_task'>;
}
declare module 'jake/lib/utils/index.js' {
  declare module.exports: $Exports<'jake/lib/utils/index'>;
}
declare module 'jake/lib/utils/logger.js' {
  declare module.exports: $Exports<'jake/lib/utils/logger'>;
}
declare module 'jake/lib/watch_task.js' {
  declare module.exports: $Exports<'jake/lib/watch_task'>;
}
declare module 'jake/test/concurrent.js' {
  declare module.exports: $Exports<'jake/test/concurrent'>;
}
declare module 'jake/test/exec.js' {
  declare module.exports: $Exports<'jake/test/exec'>;
}
declare module 'jake/test/file_task.js' {
  declare module.exports: $Exports<'jake/test/file_task'>;
}
declare module 'jake/test/helpers.js' {
  declare module.exports: $Exports<'jake/test/helpers'>;
}
declare module 'jake/test/namespace.js' {
  declare module.exports: $Exports<'jake/test/namespace'>;
}
declare module 'jake/test/parseargs.js' {
  declare module.exports: $Exports<'jake/test/parseargs'>;
}
declare module 'jake/test/publish_task.js' {
  declare module.exports: $Exports<'jake/test/publish_task'>;
}
declare module 'jake/test/rule.js' {
  declare module.exports: $Exports<'jake/test/rule'>;
}
declare module 'jake/test/selfdep.js' {
  declare module.exports: $Exports<'jake/test/selfdep'>;
}
declare module 'jake/test/task_base.js' {
  declare module.exports: $Exports<'jake/test/task_base'>;
}
