// flow-typed signature: 4da95430b40a36ff0b0004a1a40a4580
// flow-typed version: <<STUB>>/mjml_v3.3.3/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mjml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mjml' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mjml/lib/dependencies' {
  declare module.exports: any;
}

declare module 'mjml/lib/index' {
  declare module.exports: any;
}

declare module 'mjml/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mjml/lib/dependencies.js' {
  declare module.exports: $Exports<'mjml/lib/dependencies'>;
}
declare module 'mjml/lib/index.js' {
  declare module.exports: $Exports<'mjml/lib/index'>;
}
declare module 'mjml/test.js' {
  declare module.exports: $Exports<'mjml/test'>;
}
