// flow-typed signature: 25a3e2c92424ca80e606a56b1130b4cd
// flow-typed version: <<STUB>>/multer_v2.0.0-alpha.6/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'multer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'multer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'multer/lib/error' {
  declare module.exports: any;
}

declare module 'multer/lib/file-appender' {
  declare module.exports: any;
}

declare module 'multer/lib/file-filter' {
  declare module.exports: any;
}

declare module 'multer/lib/middleware' {
  declare module.exports: any;
}

declare module 'multer/lib/read-body' {
  declare module.exports: any;
}

// Filename aliases
declare module 'multer/index' {
  declare module.exports: $Exports<'multer'>;
}
declare module 'multer/index.js' {
  declare module.exports: $Exports<'multer'>;
}
declare module 'multer/lib/error.js' {
  declare module.exports: $Exports<'multer/lib/error'>;
}
declare module 'multer/lib/file-appender.js' {
  declare module.exports: $Exports<'multer/lib/file-appender'>;
}
declare module 'multer/lib/file-filter.js' {
  declare module.exports: $Exports<'multer/lib/file-filter'>;
}
declare module 'multer/lib/middleware.js' {
  declare module.exports: $Exports<'multer/lib/middleware'>;
}
declare module 'multer/lib/read-body.js' {
  declare module.exports: $Exports<'multer/lib/read-body'>;
}
