// flow-typed signature: f6507e59d34a7258121e68bebaf36b0a
// flow-typed version: <<STUB>>/nan_v2.10.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nan'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nan' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nan/include_dirs' {
  declare module.exports: any;
}

declare module 'nan/tools/1to2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nan/include_dirs.js' {
  declare module.exports: $Exports<'nan/include_dirs'>;
}
declare module 'nan/tools/1to2.js' {
  declare module.exports: $Exports<'nan/tools/1to2'>;
}
