// flow-typed signature: cb4d3ba64e9d71c671f8e09543ef102f
// flow-typed version: <<STUB>>/normalize.css_v^5.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
