// flow-typed signature: 6ba24dbf0637b45819e0b8caa030842c
// flow-typed version: <<STUB>>/react-facebook-sdk_v1.1.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-facebook-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-facebook-sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-facebook-sdk/dist/Comments' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/CommentsCount' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/constants/ColorScheme' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/constants/CommentsOrderBy' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/constants/LikeAction' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/constants/LikeLayout' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/constants/LikeSize' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/constants/MessengerColor' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/constants/MessengerSize' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/CustomChat' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/EmbeddedPost' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/Facebook' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/FacebookProvider' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/Feed' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/index' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/InitFacebook' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/Like' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/Login' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/LoginButton' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/MessageUs' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/MessengerCheckbox' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/Page' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/Parser' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/Process' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/SendToMessenger' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/Share' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/Share.test' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/ShareButton' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/utils/clearUndefinedProperties' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/dist/utils/getCurrentHref' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/jest/setup' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/Comments' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/CommentsCount' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/constants/ColorScheme' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/constants/CommentsOrderBy' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/constants/LikeAction' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/constants/LikeLayout' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/constants/LikeSize' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/constants/MessengerColor' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/constants/MessengerSize' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/CustomChat' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/EmbeddedPost' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/Facebook' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/FacebookProvider' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/Feed' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/index' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/InitFacebook' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/Like' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/Login' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/LoginButton' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/MessageUs' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/MessengerCheckbox' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/Page' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/Parser' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/Process' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/SendToMessenger' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/Share' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/Share.test' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/ShareButton' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/utils/clearUndefinedProperties' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/lib/utils/getCurrentHref' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/Comments' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/CommentsCount' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/constants/ColorScheme' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/constants/CommentsOrderBy' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/constants/LikeAction' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/constants/LikeLayout' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/constants/LikeSize' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/constants/MessengerColor' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/constants/MessengerSize' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/CustomChat' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/EmbeddedPost' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/Facebook' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/FacebookProvider' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/Feed' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/index' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/InitFacebook' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/Like' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/Login' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/LoginButton' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/MessageUs' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/MessengerCheckbox' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/Page' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/Parser' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/Process' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/SendToMessenger' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/Share' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/Share.test' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/ShareButton' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/utils/clearUndefinedProperties' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/module/utils/getCurrentHref' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/setupJest' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/Comments' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/CommentsCount' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/constants/ColorScheme' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/constants/CommentsOrderBy' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/constants/LikeAction' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/constants/LikeLayout' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/constants/LikeSize' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/constants/MessengerColor' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/constants/MessengerSize' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/CustomChat' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/EmbeddedPost' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/Facebook' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/FacebookProvider' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/Feed' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/index' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/InitFacebook' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/Like' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/Login' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/LoginButton' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/MessageUs' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/MessengerCheckbox' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/Page' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/Parser' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/Process' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/SendToMessenger' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/Share' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/Share.test' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/ShareButton' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/utils/clearUndefinedProperties' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/src/utils/getCurrentHref' {
  declare module.exports: any;
}

declare module 'react-facebook-sdk/tempPolyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-facebook-sdk/dist/Comments.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/Comments'>;
}
declare module 'react-facebook-sdk/dist/CommentsCount.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/CommentsCount'>;
}
declare module 'react-facebook-sdk/dist/constants/ColorScheme.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/constants/ColorScheme'>;
}
declare module 'react-facebook-sdk/dist/constants/CommentsOrderBy.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/constants/CommentsOrderBy'>;
}
declare module 'react-facebook-sdk/dist/constants/LikeAction.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/constants/LikeAction'>;
}
declare module 'react-facebook-sdk/dist/constants/LikeLayout.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/constants/LikeLayout'>;
}
declare module 'react-facebook-sdk/dist/constants/LikeSize.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/constants/LikeSize'>;
}
declare module 'react-facebook-sdk/dist/constants/MessengerColor.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/constants/MessengerColor'>;
}
declare module 'react-facebook-sdk/dist/constants/MessengerSize.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/constants/MessengerSize'>;
}
declare module 'react-facebook-sdk/dist/CustomChat.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/CustomChat'>;
}
declare module 'react-facebook-sdk/dist/EmbeddedPost.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/EmbeddedPost'>;
}
declare module 'react-facebook-sdk/dist/Facebook.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/Facebook'>;
}
declare module 'react-facebook-sdk/dist/FacebookProvider.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/FacebookProvider'>;
}
declare module 'react-facebook-sdk/dist/Feed.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/Feed'>;
}
declare module 'react-facebook-sdk/dist/index.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/index'>;
}
declare module 'react-facebook-sdk/dist/InitFacebook.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/InitFacebook'>;
}
declare module 'react-facebook-sdk/dist/Like.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/Like'>;
}
declare module 'react-facebook-sdk/dist/Login.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/Login'>;
}
declare module 'react-facebook-sdk/dist/LoginButton.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/LoginButton'>;
}
declare module 'react-facebook-sdk/dist/MessageUs.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/MessageUs'>;
}
declare module 'react-facebook-sdk/dist/MessengerCheckbox.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/MessengerCheckbox'>;
}
declare module 'react-facebook-sdk/dist/Page.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/Page'>;
}
declare module 'react-facebook-sdk/dist/Parser.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/Parser'>;
}
declare module 'react-facebook-sdk/dist/Process.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/Process'>;
}
declare module 'react-facebook-sdk/dist/SendToMessenger.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/SendToMessenger'>;
}
declare module 'react-facebook-sdk/dist/Share.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/Share'>;
}
declare module 'react-facebook-sdk/dist/Share.test.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/Share.test'>;
}
declare module 'react-facebook-sdk/dist/ShareButton.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/ShareButton'>;
}
declare module 'react-facebook-sdk/dist/utils/clearUndefinedProperties.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/utils/clearUndefinedProperties'>;
}
declare module 'react-facebook-sdk/dist/utils/getCurrentHref.js' {
  declare module.exports: $Exports<'react-facebook-sdk/dist/utils/getCurrentHref'>;
}
declare module 'react-facebook-sdk/jest/setup.js' {
  declare module.exports: $Exports<'react-facebook-sdk/jest/setup'>;
}
declare module 'react-facebook-sdk/lib/Comments.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/Comments'>;
}
declare module 'react-facebook-sdk/lib/CommentsCount.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/CommentsCount'>;
}
declare module 'react-facebook-sdk/lib/constants/ColorScheme.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/constants/ColorScheme'>;
}
declare module 'react-facebook-sdk/lib/constants/CommentsOrderBy.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/constants/CommentsOrderBy'>;
}
declare module 'react-facebook-sdk/lib/constants/LikeAction.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/constants/LikeAction'>;
}
declare module 'react-facebook-sdk/lib/constants/LikeLayout.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/constants/LikeLayout'>;
}
declare module 'react-facebook-sdk/lib/constants/LikeSize.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/constants/LikeSize'>;
}
declare module 'react-facebook-sdk/lib/constants/MessengerColor.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/constants/MessengerColor'>;
}
declare module 'react-facebook-sdk/lib/constants/MessengerSize.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/constants/MessengerSize'>;
}
declare module 'react-facebook-sdk/lib/CustomChat.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/CustomChat'>;
}
declare module 'react-facebook-sdk/lib/EmbeddedPost.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/EmbeddedPost'>;
}
declare module 'react-facebook-sdk/lib/Facebook.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/Facebook'>;
}
declare module 'react-facebook-sdk/lib/FacebookProvider.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/FacebookProvider'>;
}
declare module 'react-facebook-sdk/lib/Feed.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/Feed'>;
}
declare module 'react-facebook-sdk/lib/index.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/index'>;
}
declare module 'react-facebook-sdk/lib/InitFacebook.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/InitFacebook'>;
}
declare module 'react-facebook-sdk/lib/Like.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/Like'>;
}
declare module 'react-facebook-sdk/lib/Login.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/Login'>;
}
declare module 'react-facebook-sdk/lib/LoginButton.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/LoginButton'>;
}
declare module 'react-facebook-sdk/lib/MessageUs.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/MessageUs'>;
}
declare module 'react-facebook-sdk/lib/MessengerCheckbox.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/MessengerCheckbox'>;
}
declare module 'react-facebook-sdk/lib/Page.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/Page'>;
}
declare module 'react-facebook-sdk/lib/Parser.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/Parser'>;
}
declare module 'react-facebook-sdk/lib/Process.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/Process'>;
}
declare module 'react-facebook-sdk/lib/SendToMessenger.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/SendToMessenger'>;
}
declare module 'react-facebook-sdk/lib/Share.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/Share'>;
}
declare module 'react-facebook-sdk/lib/Share.test.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/Share.test'>;
}
declare module 'react-facebook-sdk/lib/ShareButton.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/ShareButton'>;
}
declare module 'react-facebook-sdk/lib/utils/clearUndefinedProperties.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/utils/clearUndefinedProperties'>;
}
declare module 'react-facebook-sdk/lib/utils/getCurrentHref.js' {
  declare module.exports: $Exports<'react-facebook-sdk/lib/utils/getCurrentHref'>;
}
declare module 'react-facebook-sdk/module/Comments.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/Comments'>;
}
declare module 'react-facebook-sdk/module/CommentsCount.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/CommentsCount'>;
}
declare module 'react-facebook-sdk/module/constants/ColorScheme.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/constants/ColorScheme'>;
}
declare module 'react-facebook-sdk/module/constants/CommentsOrderBy.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/constants/CommentsOrderBy'>;
}
declare module 'react-facebook-sdk/module/constants/LikeAction.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/constants/LikeAction'>;
}
declare module 'react-facebook-sdk/module/constants/LikeLayout.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/constants/LikeLayout'>;
}
declare module 'react-facebook-sdk/module/constants/LikeSize.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/constants/LikeSize'>;
}
declare module 'react-facebook-sdk/module/constants/MessengerColor.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/constants/MessengerColor'>;
}
declare module 'react-facebook-sdk/module/constants/MessengerSize.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/constants/MessengerSize'>;
}
declare module 'react-facebook-sdk/module/CustomChat.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/CustomChat'>;
}
declare module 'react-facebook-sdk/module/EmbeddedPost.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/EmbeddedPost'>;
}
declare module 'react-facebook-sdk/module/Facebook.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/Facebook'>;
}
declare module 'react-facebook-sdk/module/FacebookProvider.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/FacebookProvider'>;
}
declare module 'react-facebook-sdk/module/Feed.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/Feed'>;
}
declare module 'react-facebook-sdk/module/index.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/index'>;
}
declare module 'react-facebook-sdk/module/InitFacebook.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/InitFacebook'>;
}
declare module 'react-facebook-sdk/module/Like.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/Like'>;
}
declare module 'react-facebook-sdk/module/Login.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/Login'>;
}
declare module 'react-facebook-sdk/module/LoginButton.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/LoginButton'>;
}
declare module 'react-facebook-sdk/module/MessageUs.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/MessageUs'>;
}
declare module 'react-facebook-sdk/module/MessengerCheckbox.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/MessengerCheckbox'>;
}
declare module 'react-facebook-sdk/module/Page.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/Page'>;
}
declare module 'react-facebook-sdk/module/Parser.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/Parser'>;
}
declare module 'react-facebook-sdk/module/Process.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/Process'>;
}
declare module 'react-facebook-sdk/module/SendToMessenger.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/SendToMessenger'>;
}
declare module 'react-facebook-sdk/module/Share.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/Share'>;
}
declare module 'react-facebook-sdk/module/Share.test.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/Share.test'>;
}
declare module 'react-facebook-sdk/module/ShareButton.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/ShareButton'>;
}
declare module 'react-facebook-sdk/module/utils/clearUndefinedProperties.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/utils/clearUndefinedProperties'>;
}
declare module 'react-facebook-sdk/module/utils/getCurrentHref.js' {
  declare module.exports: $Exports<'react-facebook-sdk/module/utils/getCurrentHref'>;
}
declare module 'react-facebook-sdk/setupJest.js' {
  declare module.exports: $Exports<'react-facebook-sdk/setupJest'>;
}
declare module 'react-facebook-sdk/src/Comments.jsx' {
  declare module.exports: $Exports<'react-facebook-sdk/src/Comments'>;
}
declare module 'react-facebook-sdk/src/CommentsCount.jsx' {
  declare module.exports: $Exports<'react-facebook-sdk/src/CommentsCount'>;
}
declare module 'react-facebook-sdk/src/constants/ColorScheme.js' {
  declare module.exports: $Exports<'react-facebook-sdk/src/constants/ColorScheme'>;
}
declare module 'react-facebook-sdk/src/constants/CommentsOrderBy.js' {
  declare module.exports: $Exports<'react-facebook-sdk/src/constants/CommentsOrderBy'>;
}
declare module 'react-facebook-sdk/src/constants/LikeAction.js' {
  declare module.exports: $Exports<'react-facebook-sdk/src/constants/LikeAction'>;
}
declare module 'react-facebook-sdk/src/constants/LikeLayout.js' {
  declare module.exports: $Exports<'react-facebook-sdk/src/constants/LikeLayout'>;
}
declare module 'react-facebook-sdk/src/constants/LikeSize.js' {
  declare module.exports: $Exports<'react-facebook-sdk/src/constants/LikeSize'>;
}
declare module 'react-facebook-sdk/src/constants/MessengerColor.js' {
  declare module.exports: $Exports<'react-facebook-sdk/src/constants/MessengerColor'>;
}
declare module 'react-facebook-sdk/src/constants/MessengerSize.js' {
  declare module.exports: $Exports<'react-facebook-sdk/src/constants/MessengerSize'>;
}
declare module 'react-facebook-sdk/src/CustomChat.jsx' {
  declare module.exports: $Exports<'react-facebook-sdk/src/CustomChat'>;
}
declare module 'react-facebook-sdk/src/EmbeddedPost.jsx' {
  declare module.exports: $Exports<'react-facebook-sdk/src/EmbeddedPost'>;
}
declare module 'react-facebook-sdk/src/Facebook.js' {
  declare module.exports: $Exports<'react-facebook-sdk/src/Facebook'>;
}
declare module 'react-facebook-sdk/src/FacebookProvider.jsx' {
  declare module.exports: $Exports<'react-facebook-sdk/src/FacebookProvider'>;
}
declare module 'react-facebook-sdk/src/Feed.jsx' {
  declare module.exports: $Exports<'react-facebook-sdk/src/Feed'>;
}
declare module 'react-facebook-sdk/src/index.js' {
  declare module.exports: $Exports<'react-facebook-sdk/src/index'>;
}
declare module 'react-facebook-sdk/src/InitFacebook.jsx' {
  declare module.exports: $Exports<'react-facebook-sdk/src/InitFacebook'>;
}
declare module 'react-facebook-sdk/src/Like.jsx' {
  declare module.exports: $Exports<'react-facebook-sdk/src/Like'>;
}
declare module 'react-facebook-sdk/src/Login.jsx' {
  declare module.exports: $Exports<'react-facebook-sdk/src/Login'>;
}
declare module 'react-facebook-sdk/src/LoginButton.jsx' {
  declare module.exports: $Exports<'react-facebook-sdk/src/LoginButton'>;
}
declare module 'react-facebook-sdk/src/MessageUs.jsx' {
  declare module.exports: $Exports<'react-facebook-sdk/src/MessageUs'>;
}
declare module 'react-facebook-sdk/src/MessengerCheckbox.jsx' {
  declare module.exports: $Exports<'react-facebook-sdk/src/MessengerCheckbox'>;
}
declare module 'react-facebook-sdk/src/Page.jsx' {
  declare module.exports: $Exports<'react-facebook-sdk/src/Page'>;
}
declare module 'react-facebook-sdk/src/Parser.jsx' {
  declare module.exports: $Exports<'react-facebook-sdk/src/Parser'>;
}
declare module 'react-facebook-sdk/src/Process.jsx' {
  declare module.exports: $Exports<'react-facebook-sdk/src/Process'>;
}
declare module 'react-facebook-sdk/src/SendToMessenger.jsx' {
  declare module.exports: $Exports<'react-facebook-sdk/src/SendToMessenger'>;
}
declare module 'react-facebook-sdk/src/Share.jsx' {
  declare module.exports: $Exports<'react-facebook-sdk/src/Share'>;
}
declare module 'react-facebook-sdk/src/Share.test.jsx' {
  declare module.exports: $Exports<'react-facebook-sdk/src/Share.test'>;
}
declare module 'react-facebook-sdk/src/ShareButton.jsx' {
  declare module.exports: $Exports<'react-facebook-sdk/src/ShareButton'>;
}
declare module 'react-facebook-sdk/src/utils/clearUndefinedProperties.js' {
  declare module.exports: $Exports<'react-facebook-sdk/src/utils/clearUndefinedProperties'>;
}
declare module 'react-facebook-sdk/src/utils/getCurrentHref.js' {
  declare module.exports: $Exports<'react-facebook-sdk/src/utils/getCurrentHref'>;
}
declare module 'react-facebook-sdk/tempPolyfill.js' {
  declare module.exports: $Exports<'react-facebook-sdk/tempPolyfill'>;
}
