// flow-typed signature: 88ca984066868089a8728bfc49c031db
// flow-typed version: <<STUB>>/transloadit_v1.10.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'transloadit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'transloadit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'transloadit/examples/convert_to_webp' {
  declare module.exports: any;
}

declare module 'transloadit/examples/fetch_costs_of_all_assemblies_in_timeframe' {
  declare module.exports: any;
}

declare module 'transloadit/examples/list_assembly_notifications' {
  declare module.exports: any;
}

declare module 'transloadit/examples/resize_an_image' {
  declare module.exports: any;
}

declare module 'transloadit/examples/template_api' {
  declare module.exports: any;
}

declare module 'transloadit/examples/upload_a_file' {
  declare module.exports: any;
}

declare module 'transloadit/lib/PaginationStream' {
  declare module.exports: any;
}

declare module 'transloadit/lib/TransloaditClient' {
  declare module.exports: any;
}

declare module 'transloadit/src/PaginationStream' {
  declare module.exports: any;
}

declare module 'transloadit/src/TransloaditClient' {
  declare module.exports: any;
}

declare module 'transloadit/test/gently-preamble' {
  declare module.exports: any;
}

declare module 'transloadit/test/integration' {
  declare module.exports: any;
}

declare module 'transloadit/test/test-pagination-stream' {
  declare module.exports: any;
}

declare module 'transloadit/test/test-transloadit-client' {
  declare module.exports: any;
}

// Filename aliases
declare module 'transloadit/examples/convert_to_webp.js' {
  declare module.exports: $Exports<'transloadit/examples/convert_to_webp'>;
}
declare module 'transloadit/examples/fetch_costs_of_all_assemblies_in_timeframe.js' {
  declare module.exports: $Exports<'transloadit/examples/fetch_costs_of_all_assemblies_in_timeframe'>;
}
declare module 'transloadit/examples/list_assembly_notifications.js' {
  declare module.exports: $Exports<'transloadit/examples/list_assembly_notifications'>;
}
declare module 'transloadit/examples/resize_an_image.js' {
  declare module.exports: $Exports<'transloadit/examples/resize_an_image'>;
}
declare module 'transloadit/examples/template_api.js' {
  declare module.exports: $Exports<'transloadit/examples/template_api'>;
}
declare module 'transloadit/examples/upload_a_file.js' {
  declare module.exports: $Exports<'transloadit/examples/upload_a_file'>;
}
declare module 'transloadit/index' {
  declare module.exports: $Exports<'transloadit'>;
}
declare module 'transloadit/index.js' {
  declare module.exports: $Exports<'transloadit'>;
}
declare module 'transloadit/lib/PaginationStream.js' {
  declare module.exports: $Exports<'transloadit/lib/PaginationStream'>;
}
declare module 'transloadit/lib/TransloaditClient.js' {
  declare module.exports: $Exports<'transloadit/lib/TransloaditClient'>;
}
declare module 'transloadit/src/PaginationStream.js' {
  declare module.exports: $Exports<'transloadit/src/PaginationStream'>;
}
declare module 'transloadit/src/TransloaditClient.js' {
  declare module.exports: $Exports<'transloadit/src/TransloaditClient'>;
}
declare module 'transloadit/test/gently-preamble.js' {
  declare module.exports: $Exports<'transloadit/test/gently-preamble'>;
}
declare module 'transloadit/test/integration.js' {
  declare module.exports: $Exports<'transloadit/test/integration'>;
}
declare module 'transloadit/test/test-pagination-stream.js' {
  declare module.exports: $Exports<'transloadit/test/test-pagination-stream'>;
}
declare module 'transloadit/test/test-transloadit-client.js' {
  declare module.exports: $Exports<'transloadit/test/test-transloadit-client'>;
}
