// flow-typed signature: 364ba8984da40c701a5dc61a34345376
// flow-typed version: <<STUB>>/twilio_v3.17.2/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'twilio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'twilio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'twilio/lib/base/deserialize' {
  declare module.exports: any;
}

declare module 'twilio/lib/base/Domain' {
  declare module.exports: any;
}

declare module 'twilio/lib/base/obsolete' {
  declare module.exports: any;
}

declare module 'twilio/lib/base/Page' {
  declare module.exports: any;
}

declare module 'twilio/lib/base/RequestClient' {
  declare module.exports: any;
}

declare module 'twilio/lib/base/RestException' {
  declare module.exports: any;
}

declare module 'twilio/lib/base/serialize' {
  declare module.exports: any;
}

declare module 'twilio/lib/base/values' {
  declare module.exports: any;
}

declare module 'twilio/lib/base/Version' {
  declare module.exports: any;
}

declare module 'twilio/lib/http/request' {
  declare module.exports: any;
}

declare module 'twilio/lib/http/response' {
  declare module.exports: any;
}

declare module 'twilio/lib/index' {
  declare module.exports: any;
}

declare module 'twilio/lib/jwt/AccessToken' {
  declare module.exports: any;
}

declare module 'twilio/lib/jwt/ClientCapability' {
  declare module.exports: any;
}

declare module 'twilio/lib/jwt/taskrouter/TaskRouterCapability' {
  declare module.exports: any;
}

declare module 'twilio/lib/jwt/taskrouter/util' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/Accounts' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/accounts/V1' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/accounts/v1/credential' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/accounts/v1/credential/aws' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/accounts/v1/credential/publicKey' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/Api' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/V2010' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/address' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/address/dependentPhoneNumber' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/application' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/authorizedConnectApp' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/availablePhoneNumber' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/availablePhoneNumber/local' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/availablePhoneNumber/machineToMachine' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/availablePhoneNumber/mobile' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/availablePhoneNumber/national' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/availablePhoneNumber/sharedCost' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/availablePhoneNumber/tollFree' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/availablePhoneNumber/voip' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/call' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/call/feedback' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/call/feedbackSummary' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/call/notification' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/call/recording' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/conference' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/conference/participant' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/connectApp' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/incomingPhoneNumber' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/incomingPhoneNumber/assignedAddOn' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/incomingPhoneNumber/assignedAddOn/assignedAddOnExtension' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/incomingPhoneNumber/local' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/incomingPhoneNumber/mobile' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/incomingPhoneNumber/tollFree' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/key' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/message' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/message/feedback' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/message/media' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/newKey' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/newSigningKey' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/notification' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/outgoingCallerId' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/queue' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/queue/member' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/recording' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/recording/addOnResult' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/recording/addOnResult/payload' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/recording/transcription' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/shortCode' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/signingKey' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/sip' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/sip/credentialList' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/sip/credentialList/credential' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/sip/domain' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/sip/domain/credentialListMapping' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/sip/domain/ipAccessControlListMapping' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/sip/ipAccessControlList' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/sip/ipAccessControlList/ipAddress' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/token' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/transcription' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/usage' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/usage/record' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/usage/record/allTime' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/usage/record/daily' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/usage/record/lastMonth' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/usage/record/monthly' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/usage/record/thisMonth' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/usage/record/today' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/usage/record/yearly' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/usage/record/yesterday' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/usage/trigger' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/api/v2010/account/validationRequest' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/Chat' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/V1' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/v1/credential' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/v1/service' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/v1/service/channel' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/v1/service/channel/invite' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/v1/service/channel/member' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/v1/service/channel/message' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/v1/service/role' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/v1/service/user' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/v1/service/user/userChannel' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/V2' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/v2/credential' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/v2/service' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/v2/service/binding' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/v2/service/channel' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/v2/service/channel/invite' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/v2/service/channel/member' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/v2/service/channel/message' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/v2/service/channel/webhook' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/v2/service/role' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/v2/service/user' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/v2/service/user/userBinding' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/chat/v2/service/user/userChannel' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/Fax' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/fax/V1' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/fax/v1/fax' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/fax/v1/fax/faxMedia' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/IpMessaging' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/V1' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/v1/credential' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/v1/service' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/v1/service/channel' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/v1/service/channel/invite' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/v1/service/channel/member' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/v1/service/channel/message' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/v1/service/role' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/v1/service/user' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/v1/service/user/userChannel' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/V2' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/v2/credential' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/v2/service' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/v2/service/binding' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/v2/service/channel' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/v2/service/channel/invite' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/v2/service/channel/member' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/v2/service/channel/message' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/v2/service/channel/webhook' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/v2/service/role' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/v2/service/user' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/v2/service/user/userBinding' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/ipMessaging/v2/service/user/userChannel' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/Lookups' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/lookups/V1' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/lookups/v1/phoneNumber' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/Messaging' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/messaging/V1' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/messaging/v1/service' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/messaging/v1/service/alphaSender' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/messaging/v1/service/phoneNumber' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/messaging/v1/service/shortCode' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/Monitor' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/monitor/V1' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/monitor/v1/alert' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/monitor/v1/event' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/Notify' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/notify/V1' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/notify/v1/credential' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/notify/v1/service' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/notify/v1/service/binding' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/notify/v1/service/notification' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/notify/v1/service/segment' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/notify/v1/service/user' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/notify/v1/service/user/segmentMemberships' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/notify/v1/service/user/userBinding' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/Preview' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/acc_security/service' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/acc_security/service/verification' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/acc_security/service/verificationCheck' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/AccSecurity' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/bulk_exports/export' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/bulk_exports/export/day' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/bulk_exports/exportConfiguration' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/BulkExports' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/deployed_devices/fleet' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/deployed_devices/fleet/certificate' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/deployed_devices/fleet/deployment' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/deployed_devices/fleet/device' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/deployed_devices/fleet/key' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/DeployedDevices' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/hosted_numbers/authorizationDocument' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/hosted_numbers/authorizationDocument/dependentHostedNumberOrder' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/hosted_numbers/hostedNumberOrder' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/HostedNumbers' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/Marketplace' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/marketplace/availableAddOn' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/marketplace/availableAddOn/availableAddOnExtension' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/marketplace/installedAddOn' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/marketplace/installedAddOn/installedAddOnExtension' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/Proxy' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/proxy/service' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/proxy/service/phoneNumber' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/proxy/service/session' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/proxy/service/session/interaction' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/proxy/service/session/participant' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/proxy/service/session/participant/messageInteraction' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/proxy/service/shortCode' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/Studio' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/studio/flow' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/studio/flow/engagement' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/studio/flow/engagement/step' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/Sync' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/sync/service' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/sync/service/document' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/sync/service/document/documentPermission' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/sync/service/syncList' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/sync/service/syncList/syncListItem' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/sync/service/syncList/syncListPermission' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/sync/service/syncMap' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/sync/service/syncMap/syncMapItem' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/sync/service/syncMap/syncMapPermission' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/Understand' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/understand/assistant' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/understand/assistant/fieldType' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/understand/assistant/fieldType/fieldValue' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/understand/assistant/intent' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/understand/assistant/intent/field' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/understand/assistant/intent/sample' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/understand/assistant/modelBuild' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/understand/assistant/query' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/Wireless' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/wireless/command' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/wireless/ratePlan' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/wireless/sim' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/preview/wireless/sim/usage' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/Pricing' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/pricing/V1' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/pricing/v1/messaging' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/pricing/v1/messaging/country' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/pricing/v1/phoneNumber' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/pricing/v1/phoneNumber/country' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/pricing/v1/voice' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/pricing/v1/voice/country' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/pricing/v1/voice/number' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/Proxy' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/proxy/V1' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/proxy/v1/service' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/proxy/v1/service/phoneNumber' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/proxy/v1/service/session' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/proxy/v1/service/session/interaction' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/proxy/v1/service/session/participant' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/proxy/v1/service/session/participant/messageInteraction' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/proxy/v1/service/shortCode' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/Studio' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/studio/V1' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/studio/v1/flow' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/studio/v1/flow/engagement' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/studio/v1/flow/engagement/engagementContext' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/studio/v1/flow/engagement/step' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/studio/v1/flow/engagement/step/stepContext' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/Sync' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/sync/V1' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/sync/v1/service' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/sync/v1/service/document' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/sync/v1/service/document/documentPermission' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/sync/v1/service/syncList' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/sync/v1/service/syncList/syncListItem' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/sync/v1/service/syncList/syncListPermission' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/sync/v1/service/syncMap' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/sync/v1/service/syncMap/syncMapItem' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/sync/v1/service/syncMap/syncMapPermission' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/sync/v1/service/syncStream' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/sync/v1/service/syncStream/streamMessage' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/Taskrouter' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/V1' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/activity' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/event' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/task' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/task/reservation' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/taskChannel' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/taskQueue' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/taskQueue/taskQueueCumulativeStatistics' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/taskQueue/taskQueueRealTimeStatistics' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/taskQueue/taskQueuesStatistics' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/taskQueue/taskQueueStatistics' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/worker' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/worker/reservation' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/worker/workerChannel' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/worker/workersCumulativeStatistics' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/worker/workersRealTimeStatistics' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/worker/workersStatistics' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/worker/workerStatistics' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/workflow' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/workflow/workflowCumulativeStatistics' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/workflow/workflowRealTimeStatistics' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/workflow/workflowStatistics' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/workspaceCumulativeStatistics' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/workspaceRealTimeStatistics' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/taskrouter/v1/workspace/workspaceStatistics' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/Trunking' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/trunking/V1' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/trunking/v1/trunk' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/trunking/v1/trunk/credentialList' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/trunking/v1/trunk/ipAccessControlList' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/trunking/v1/trunk/originationUrl' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/trunking/v1/trunk/phoneNumber' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/Twilio' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/Video' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/video/V1' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/video/v1/composition' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/video/v1/recording' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/video/v1/room' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/video/v1/room/recording' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/video/v1/room/roomParticipant' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/video/v1/room/roomParticipant/roomParticipantPublishedTrack' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/video/v1/room/roomParticipant/roomParticipantSubscribedTrack' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/Wireless' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/wireless/V1' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/wireless/v1/command' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/wireless/v1/ratePlan' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/wireless/v1/sim' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/wireless/v1/sim/dataSession' {
  declare module.exports: any;
}

declare module 'twilio/lib/rest/wireless/v1/sim/usageRecord' {
  declare module.exports: any;
}

declare module 'twilio/lib/twiml/FaxResponse' {
  declare module.exports: any;
}

declare module 'twilio/lib/twiml/MessagingResponse' {
  declare module.exports: any;
}

declare module 'twilio/lib/twiml/VoiceResponse' {
  declare module.exports: any;
}

declare module 'twilio/lib/webhooks/webhooks' {
  declare module.exports: any;
}

// Filename aliases
declare module 'twilio/index' {
  declare module.exports: $Exports<'twilio'>;
}
declare module 'twilio/index.js' {
  declare module.exports: $Exports<'twilio'>;
}
declare module 'twilio/lib/base/deserialize.js' {
  declare module.exports: $Exports<'twilio/lib/base/deserialize'>;
}
declare module 'twilio/lib/base/Domain.js' {
  declare module.exports: $Exports<'twilio/lib/base/Domain'>;
}
declare module 'twilio/lib/base/obsolete.js' {
  declare module.exports: $Exports<'twilio/lib/base/obsolete'>;
}
declare module 'twilio/lib/base/Page.js' {
  declare module.exports: $Exports<'twilio/lib/base/Page'>;
}
declare module 'twilio/lib/base/RequestClient.js' {
  declare module.exports: $Exports<'twilio/lib/base/RequestClient'>;
}
declare module 'twilio/lib/base/RestException.js' {
  declare module.exports: $Exports<'twilio/lib/base/RestException'>;
}
declare module 'twilio/lib/base/serialize.js' {
  declare module.exports: $Exports<'twilio/lib/base/serialize'>;
}
declare module 'twilio/lib/base/values.js' {
  declare module.exports: $Exports<'twilio/lib/base/values'>;
}
declare module 'twilio/lib/base/Version.js' {
  declare module.exports: $Exports<'twilio/lib/base/Version'>;
}
declare module 'twilio/lib/http/request.js' {
  declare module.exports: $Exports<'twilio/lib/http/request'>;
}
declare module 'twilio/lib/http/response.js' {
  declare module.exports: $Exports<'twilio/lib/http/response'>;
}
declare module 'twilio/lib/index.js' {
  declare module.exports: $Exports<'twilio/lib/index'>;
}
declare module 'twilio/lib/jwt/AccessToken.js' {
  declare module.exports: $Exports<'twilio/lib/jwt/AccessToken'>;
}
declare module 'twilio/lib/jwt/ClientCapability.js' {
  declare module.exports: $Exports<'twilio/lib/jwt/ClientCapability'>;
}
declare module 'twilio/lib/jwt/taskrouter/TaskRouterCapability.js' {
  declare module.exports: $Exports<'twilio/lib/jwt/taskrouter/TaskRouterCapability'>;
}
declare module 'twilio/lib/jwt/taskrouter/util.js' {
  declare module.exports: $Exports<'twilio/lib/jwt/taskrouter/util'>;
}
declare module 'twilio/lib/rest/Accounts.js' {
  declare module.exports: $Exports<'twilio/lib/rest/Accounts'>;
}
declare module 'twilio/lib/rest/accounts/V1.js' {
  declare module.exports: $Exports<'twilio/lib/rest/accounts/V1'>;
}
declare module 'twilio/lib/rest/accounts/v1/credential.js' {
  declare module.exports: $Exports<'twilio/lib/rest/accounts/v1/credential'>;
}
declare module 'twilio/lib/rest/accounts/v1/credential/aws.js' {
  declare module.exports: $Exports<'twilio/lib/rest/accounts/v1/credential/aws'>;
}
declare module 'twilio/lib/rest/accounts/v1/credential/publicKey.js' {
  declare module.exports: $Exports<'twilio/lib/rest/accounts/v1/credential/publicKey'>;
}
declare module 'twilio/lib/rest/Api.js' {
  declare module.exports: $Exports<'twilio/lib/rest/Api'>;
}
declare module 'twilio/lib/rest/api/V2010.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/V2010'>;
}
declare module 'twilio/lib/rest/api/v2010/account.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account'>;
}
declare module 'twilio/lib/rest/api/v2010/account/address.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/address'>;
}
declare module 'twilio/lib/rest/api/v2010/account/address/dependentPhoneNumber.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/address/dependentPhoneNumber'>;
}
declare module 'twilio/lib/rest/api/v2010/account/application.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/application'>;
}
declare module 'twilio/lib/rest/api/v2010/account/authorizedConnectApp.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/authorizedConnectApp'>;
}
declare module 'twilio/lib/rest/api/v2010/account/availablePhoneNumber.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/availablePhoneNumber'>;
}
declare module 'twilio/lib/rest/api/v2010/account/availablePhoneNumber/local.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/availablePhoneNumber/local'>;
}
declare module 'twilio/lib/rest/api/v2010/account/availablePhoneNumber/machineToMachine.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/availablePhoneNumber/machineToMachine'>;
}
declare module 'twilio/lib/rest/api/v2010/account/availablePhoneNumber/mobile.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/availablePhoneNumber/mobile'>;
}
declare module 'twilio/lib/rest/api/v2010/account/availablePhoneNumber/national.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/availablePhoneNumber/national'>;
}
declare module 'twilio/lib/rest/api/v2010/account/availablePhoneNumber/sharedCost.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/availablePhoneNumber/sharedCost'>;
}
declare module 'twilio/lib/rest/api/v2010/account/availablePhoneNumber/tollFree.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/availablePhoneNumber/tollFree'>;
}
declare module 'twilio/lib/rest/api/v2010/account/availablePhoneNumber/voip.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/availablePhoneNumber/voip'>;
}
declare module 'twilio/lib/rest/api/v2010/account/call.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/call'>;
}
declare module 'twilio/lib/rest/api/v2010/account/call/feedback.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/call/feedback'>;
}
declare module 'twilio/lib/rest/api/v2010/account/call/feedbackSummary.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/call/feedbackSummary'>;
}
declare module 'twilio/lib/rest/api/v2010/account/call/notification.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/call/notification'>;
}
declare module 'twilio/lib/rest/api/v2010/account/call/recording.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/call/recording'>;
}
declare module 'twilio/lib/rest/api/v2010/account/conference.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/conference'>;
}
declare module 'twilio/lib/rest/api/v2010/account/conference/participant.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/conference/participant'>;
}
declare module 'twilio/lib/rest/api/v2010/account/connectApp.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/connectApp'>;
}
declare module 'twilio/lib/rest/api/v2010/account/incomingPhoneNumber.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/incomingPhoneNumber'>;
}
declare module 'twilio/lib/rest/api/v2010/account/incomingPhoneNumber/assignedAddOn.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/incomingPhoneNumber/assignedAddOn'>;
}
declare module 'twilio/lib/rest/api/v2010/account/incomingPhoneNumber/assignedAddOn/assignedAddOnExtension.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/incomingPhoneNumber/assignedAddOn/assignedAddOnExtension'>;
}
declare module 'twilio/lib/rest/api/v2010/account/incomingPhoneNumber/local.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/incomingPhoneNumber/local'>;
}
declare module 'twilio/lib/rest/api/v2010/account/incomingPhoneNumber/mobile.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/incomingPhoneNumber/mobile'>;
}
declare module 'twilio/lib/rest/api/v2010/account/incomingPhoneNumber/tollFree.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/incomingPhoneNumber/tollFree'>;
}
declare module 'twilio/lib/rest/api/v2010/account/key.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/key'>;
}
declare module 'twilio/lib/rest/api/v2010/account/message.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/message'>;
}
declare module 'twilio/lib/rest/api/v2010/account/message/feedback.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/message/feedback'>;
}
declare module 'twilio/lib/rest/api/v2010/account/message/media.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/message/media'>;
}
declare module 'twilio/lib/rest/api/v2010/account/newKey.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/newKey'>;
}
declare module 'twilio/lib/rest/api/v2010/account/newSigningKey.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/newSigningKey'>;
}
declare module 'twilio/lib/rest/api/v2010/account/notification.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/notification'>;
}
declare module 'twilio/lib/rest/api/v2010/account/outgoingCallerId.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/outgoingCallerId'>;
}
declare module 'twilio/lib/rest/api/v2010/account/queue.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/queue'>;
}
declare module 'twilio/lib/rest/api/v2010/account/queue/member.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/queue/member'>;
}
declare module 'twilio/lib/rest/api/v2010/account/recording.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/recording'>;
}
declare module 'twilio/lib/rest/api/v2010/account/recording/addOnResult.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/recording/addOnResult'>;
}
declare module 'twilio/lib/rest/api/v2010/account/recording/addOnResult/payload.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/recording/addOnResult/payload'>;
}
declare module 'twilio/lib/rest/api/v2010/account/recording/transcription.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/recording/transcription'>;
}
declare module 'twilio/lib/rest/api/v2010/account/shortCode.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/shortCode'>;
}
declare module 'twilio/lib/rest/api/v2010/account/signingKey.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/signingKey'>;
}
declare module 'twilio/lib/rest/api/v2010/account/sip.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/sip'>;
}
declare module 'twilio/lib/rest/api/v2010/account/sip/credentialList.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/sip/credentialList'>;
}
declare module 'twilio/lib/rest/api/v2010/account/sip/credentialList/credential.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/sip/credentialList/credential'>;
}
declare module 'twilio/lib/rest/api/v2010/account/sip/domain.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/sip/domain'>;
}
declare module 'twilio/lib/rest/api/v2010/account/sip/domain/credentialListMapping.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/sip/domain/credentialListMapping'>;
}
declare module 'twilio/lib/rest/api/v2010/account/sip/domain/ipAccessControlListMapping.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/sip/domain/ipAccessControlListMapping'>;
}
declare module 'twilio/lib/rest/api/v2010/account/sip/ipAccessControlList.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/sip/ipAccessControlList'>;
}
declare module 'twilio/lib/rest/api/v2010/account/sip/ipAccessControlList/ipAddress.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/sip/ipAccessControlList/ipAddress'>;
}
declare module 'twilio/lib/rest/api/v2010/account/token.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/token'>;
}
declare module 'twilio/lib/rest/api/v2010/account/transcription.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/transcription'>;
}
declare module 'twilio/lib/rest/api/v2010/account/usage.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/usage'>;
}
declare module 'twilio/lib/rest/api/v2010/account/usage/record.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/usage/record'>;
}
declare module 'twilio/lib/rest/api/v2010/account/usage/record/allTime.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/usage/record/allTime'>;
}
declare module 'twilio/lib/rest/api/v2010/account/usage/record/daily.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/usage/record/daily'>;
}
declare module 'twilio/lib/rest/api/v2010/account/usage/record/lastMonth.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/usage/record/lastMonth'>;
}
declare module 'twilio/lib/rest/api/v2010/account/usage/record/monthly.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/usage/record/monthly'>;
}
declare module 'twilio/lib/rest/api/v2010/account/usage/record/thisMonth.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/usage/record/thisMonth'>;
}
declare module 'twilio/lib/rest/api/v2010/account/usage/record/today.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/usage/record/today'>;
}
declare module 'twilio/lib/rest/api/v2010/account/usage/record/yearly.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/usage/record/yearly'>;
}
declare module 'twilio/lib/rest/api/v2010/account/usage/record/yesterday.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/usage/record/yesterday'>;
}
declare module 'twilio/lib/rest/api/v2010/account/usage/trigger.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/usage/trigger'>;
}
declare module 'twilio/lib/rest/api/v2010/account/validationRequest.js' {
  declare module.exports: $Exports<'twilio/lib/rest/api/v2010/account/validationRequest'>;
}
declare module 'twilio/lib/rest/Chat.js' {
  declare module.exports: $Exports<'twilio/lib/rest/Chat'>;
}
declare module 'twilio/lib/rest/chat/V1.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/V1'>;
}
declare module 'twilio/lib/rest/chat/v1/credential.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/v1/credential'>;
}
declare module 'twilio/lib/rest/chat/v1/service.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/v1/service'>;
}
declare module 'twilio/lib/rest/chat/v1/service/channel.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/v1/service/channel'>;
}
declare module 'twilio/lib/rest/chat/v1/service/channel/invite.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/v1/service/channel/invite'>;
}
declare module 'twilio/lib/rest/chat/v1/service/channel/member.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/v1/service/channel/member'>;
}
declare module 'twilio/lib/rest/chat/v1/service/channel/message.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/v1/service/channel/message'>;
}
declare module 'twilio/lib/rest/chat/v1/service/role.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/v1/service/role'>;
}
declare module 'twilio/lib/rest/chat/v1/service/user.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/v1/service/user'>;
}
declare module 'twilio/lib/rest/chat/v1/service/user/userChannel.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/v1/service/user/userChannel'>;
}
declare module 'twilio/lib/rest/chat/V2.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/V2'>;
}
declare module 'twilio/lib/rest/chat/v2/credential.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/v2/credential'>;
}
declare module 'twilio/lib/rest/chat/v2/service.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/v2/service'>;
}
declare module 'twilio/lib/rest/chat/v2/service/binding.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/v2/service/binding'>;
}
declare module 'twilio/lib/rest/chat/v2/service/channel.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/v2/service/channel'>;
}
declare module 'twilio/lib/rest/chat/v2/service/channel/invite.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/v2/service/channel/invite'>;
}
declare module 'twilio/lib/rest/chat/v2/service/channel/member.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/v2/service/channel/member'>;
}
declare module 'twilio/lib/rest/chat/v2/service/channel/message.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/v2/service/channel/message'>;
}
declare module 'twilio/lib/rest/chat/v2/service/channel/webhook.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/v2/service/channel/webhook'>;
}
declare module 'twilio/lib/rest/chat/v2/service/role.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/v2/service/role'>;
}
declare module 'twilio/lib/rest/chat/v2/service/user.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/v2/service/user'>;
}
declare module 'twilio/lib/rest/chat/v2/service/user/userBinding.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/v2/service/user/userBinding'>;
}
declare module 'twilio/lib/rest/chat/v2/service/user/userChannel.js' {
  declare module.exports: $Exports<'twilio/lib/rest/chat/v2/service/user/userChannel'>;
}
declare module 'twilio/lib/rest/Fax.js' {
  declare module.exports: $Exports<'twilio/lib/rest/Fax'>;
}
declare module 'twilio/lib/rest/fax/V1.js' {
  declare module.exports: $Exports<'twilio/lib/rest/fax/V1'>;
}
declare module 'twilio/lib/rest/fax/v1/fax.js' {
  declare module.exports: $Exports<'twilio/lib/rest/fax/v1/fax'>;
}
declare module 'twilio/lib/rest/fax/v1/fax/faxMedia.js' {
  declare module.exports: $Exports<'twilio/lib/rest/fax/v1/fax/faxMedia'>;
}
declare module 'twilio/lib/rest/IpMessaging.js' {
  declare module.exports: $Exports<'twilio/lib/rest/IpMessaging'>;
}
declare module 'twilio/lib/rest/ipMessaging/V1.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/V1'>;
}
declare module 'twilio/lib/rest/ipMessaging/v1/credential.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/v1/credential'>;
}
declare module 'twilio/lib/rest/ipMessaging/v1/service.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/v1/service'>;
}
declare module 'twilio/lib/rest/ipMessaging/v1/service/channel.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/v1/service/channel'>;
}
declare module 'twilio/lib/rest/ipMessaging/v1/service/channel/invite.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/v1/service/channel/invite'>;
}
declare module 'twilio/lib/rest/ipMessaging/v1/service/channel/member.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/v1/service/channel/member'>;
}
declare module 'twilio/lib/rest/ipMessaging/v1/service/channel/message.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/v1/service/channel/message'>;
}
declare module 'twilio/lib/rest/ipMessaging/v1/service/role.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/v1/service/role'>;
}
declare module 'twilio/lib/rest/ipMessaging/v1/service/user.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/v1/service/user'>;
}
declare module 'twilio/lib/rest/ipMessaging/v1/service/user/userChannel.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/v1/service/user/userChannel'>;
}
declare module 'twilio/lib/rest/ipMessaging/V2.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/V2'>;
}
declare module 'twilio/lib/rest/ipMessaging/v2/credential.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/v2/credential'>;
}
declare module 'twilio/lib/rest/ipMessaging/v2/service.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/v2/service'>;
}
declare module 'twilio/lib/rest/ipMessaging/v2/service/binding.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/v2/service/binding'>;
}
declare module 'twilio/lib/rest/ipMessaging/v2/service/channel.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/v2/service/channel'>;
}
declare module 'twilio/lib/rest/ipMessaging/v2/service/channel/invite.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/v2/service/channel/invite'>;
}
declare module 'twilio/lib/rest/ipMessaging/v2/service/channel/member.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/v2/service/channel/member'>;
}
declare module 'twilio/lib/rest/ipMessaging/v2/service/channel/message.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/v2/service/channel/message'>;
}
declare module 'twilio/lib/rest/ipMessaging/v2/service/channel/webhook.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/v2/service/channel/webhook'>;
}
declare module 'twilio/lib/rest/ipMessaging/v2/service/role.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/v2/service/role'>;
}
declare module 'twilio/lib/rest/ipMessaging/v2/service/user.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/v2/service/user'>;
}
declare module 'twilio/lib/rest/ipMessaging/v2/service/user/userBinding.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/v2/service/user/userBinding'>;
}
declare module 'twilio/lib/rest/ipMessaging/v2/service/user/userChannel.js' {
  declare module.exports: $Exports<'twilio/lib/rest/ipMessaging/v2/service/user/userChannel'>;
}
declare module 'twilio/lib/rest/Lookups.js' {
  declare module.exports: $Exports<'twilio/lib/rest/Lookups'>;
}
declare module 'twilio/lib/rest/lookups/V1.js' {
  declare module.exports: $Exports<'twilio/lib/rest/lookups/V1'>;
}
declare module 'twilio/lib/rest/lookups/v1/phoneNumber.js' {
  declare module.exports: $Exports<'twilio/lib/rest/lookups/v1/phoneNumber'>;
}
declare module 'twilio/lib/rest/Messaging.js' {
  declare module.exports: $Exports<'twilio/lib/rest/Messaging'>;
}
declare module 'twilio/lib/rest/messaging/V1.js' {
  declare module.exports: $Exports<'twilio/lib/rest/messaging/V1'>;
}
declare module 'twilio/lib/rest/messaging/v1/service.js' {
  declare module.exports: $Exports<'twilio/lib/rest/messaging/v1/service'>;
}
declare module 'twilio/lib/rest/messaging/v1/service/alphaSender.js' {
  declare module.exports: $Exports<'twilio/lib/rest/messaging/v1/service/alphaSender'>;
}
declare module 'twilio/lib/rest/messaging/v1/service/phoneNumber.js' {
  declare module.exports: $Exports<'twilio/lib/rest/messaging/v1/service/phoneNumber'>;
}
declare module 'twilio/lib/rest/messaging/v1/service/shortCode.js' {
  declare module.exports: $Exports<'twilio/lib/rest/messaging/v1/service/shortCode'>;
}
declare module 'twilio/lib/rest/Monitor.js' {
  declare module.exports: $Exports<'twilio/lib/rest/Monitor'>;
}
declare module 'twilio/lib/rest/monitor/V1.js' {
  declare module.exports: $Exports<'twilio/lib/rest/monitor/V1'>;
}
declare module 'twilio/lib/rest/monitor/v1/alert.js' {
  declare module.exports: $Exports<'twilio/lib/rest/monitor/v1/alert'>;
}
declare module 'twilio/lib/rest/monitor/v1/event.js' {
  declare module.exports: $Exports<'twilio/lib/rest/monitor/v1/event'>;
}
declare module 'twilio/lib/rest/Notify.js' {
  declare module.exports: $Exports<'twilio/lib/rest/Notify'>;
}
declare module 'twilio/lib/rest/notify/V1.js' {
  declare module.exports: $Exports<'twilio/lib/rest/notify/V1'>;
}
declare module 'twilio/lib/rest/notify/v1/credential.js' {
  declare module.exports: $Exports<'twilio/lib/rest/notify/v1/credential'>;
}
declare module 'twilio/lib/rest/notify/v1/service.js' {
  declare module.exports: $Exports<'twilio/lib/rest/notify/v1/service'>;
}
declare module 'twilio/lib/rest/notify/v1/service/binding.js' {
  declare module.exports: $Exports<'twilio/lib/rest/notify/v1/service/binding'>;
}
declare module 'twilio/lib/rest/notify/v1/service/notification.js' {
  declare module.exports: $Exports<'twilio/lib/rest/notify/v1/service/notification'>;
}
declare module 'twilio/lib/rest/notify/v1/service/segment.js' {
  declare module.exports: $Exports<'twilio/lib/rest/notify/v1/service/segment'>;
}
declare module 'twilio/lib/rest/notify/v1/service/user.js' {
  declare module.exports: $Exports<'twilio/lib/rest/notify/v1/service/user'>;
}
declare module 'twilio/lib/rest/notify/v1/service/user/segmentMemberships.js' {
  declare module.exports: $Exports<'twilio/lib/rest/notify/v1/service/user/segmentMemberships'>;
}
declare module 'twilio/lib/rest/notify/v1/service/user/userBinding.js' {
  declare module.exports: $Exports<'twilio/lib/rest/notify/v1/service/user/userBinding'>;
}
declare module 'twilio/lib/rest/Preview.js' {
  declare module.exports: $Exports<'twilio/lib/rest/Preview'>;
}
declare module 'twilio/lib/rest/preview/acc_security/service.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/acc_security/service'>;
}
declare module 'twilio/lib/rest/preview/acc_security/service/verification.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/acc_security/service/verification'>;
}
declare module 'twilio/lib/rest/preview/acc_security/service/verificationCheck.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/acc_security/service/verificationCheck'>;
}
declare module 'twilio/lib/rest/preview/AccSecurity.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/AccSecurity'>;
}
declare module 'twilio/lib/rest/preview/bulk_exports/export.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/bulk_exports/export'>;
}
declare module 'twilio/lib/rest/preview/bulk_exports/export/day.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/bulk_exports/export/day'>;
}
declare module 'twilio/lib/rest/preview/bulk_exports/exportConfiguration.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/bulk_exports/exportConfiguration'>;
}
declare module 'twilio/lib/rest/preview/BulkExports.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/BulkExports'>;
}
declare module 'twilio/lib/rest/preview/deployed_devices/fleet.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/deployed_devices/fleet'>;
}
declare module 'twilio/lib/rest/preview/deployed_devices/fleet/certificate.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/deployed_devices/fleet/certificate'>;
}
declare module 'twilio/lib/rest/preview/deployed_devices/fleet/deployment.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/deployed_devices/fleet/deployment'>;
}
declare module 'twilio/lib/rest/preview/deployed_devices/fleet/device.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/deployed_devices/fleet/device'>;
}
declare module 'twilio/lib/rest/preview/deployed_devices/fleet/key.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/deployed_devices/fleet/key'>;
}
declare module 'twilio/lib/rest/preview/DeployedDevices.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/DeployedDevices'>;
}
declare module 'twilio/lib/rest/preview/hosted_numbers/authorizationDocument.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/hosted_numbers/authorizationDocument'>;
}
declare module 'twilio/lib/rest/preview/hosted_numbers/authorizationDocument/dependentHostedNumberOrder.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/hosted_numbers/authorizationDocument/dependentHostedNumberOrder'>;
}
declare module 'twilio/lib/rest/preview/hosted_numbers/hostedNumberOrder.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/hosted_numbers/hostedNumberOrder'>;
}
declare module 'twilio/lib/rest/preview/HostedNumbers.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/HostedNumbers'>;
}
declare module 'twilio/lib/rest/preview/Marketplace.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/Marketplace'>;
}
declare module 'twilio/lib/rest/preview/marketplace/availableAddOn.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/marketplace/availableAddOn'>;
}
declare module 'twilio/lib/rest/preview/marketplace/availableAddOn/availableAddOnExtension.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/marketplace/availableAddOn/availableAddOnExtension'>;
}
declare module 'twilio/lib/rest/preview/marketplace/installedAddOn.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/marketplace/installedAddOn'>;
}
declare module 'twilio/lib/rest/preview/marketplace/installedAddOn/installedAddOnExtension.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/marketplace/installedAddOn/installedAddOnExtension'>;
}
declare module 'twilio/lib/rest/preview/Proxy.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/Proxy'>;
}
declare module 'twilio/lib/rest/preview/proxy/service.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/proxy/service'>;
}
declare module 'twilio/lib/rest/preview/proxy/service/phoneNumber.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/proxy/service/phoneNumber'>;
}
declare module 'twilio/lib/rest/preview/proxy/service/session.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/proxy/service/session'>;
}
declare module 'twilio/lib/rest/preview/proxy/service/session/interaction.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/proxy/service/session/interaction'>;
}
declare module 'twilio/lib/rest/preview/proxy/service/session/participant.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/proxy/service/session/participant'>;
}
declare module 'twilio/lib/rest/preview/proxy/service/session/participant/messageInteraction.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/proxy/service/session/participant/messageInteraction'>;
}
declare module 'twilio/lib/rest/preview/proxy/service/shortCode.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/proxy/service/shortCode'>;
}
declare module 'twilio/lib/rest/preview/Studio.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/Studio'>;
}
declare module 'twilio/lib/rest/preview/studio/flow.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/studio/flow'>;
}
declare module 'twilio/lib/rest/preview/studio/flow/engagement.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/studio/flow/engagement'>;
}
declare module 'twilio/lib/rest/preview/studio/flow/engagement/step.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/studio/flow/engagement/step'>;
}
declare module 'twilio/lib/rest/preview/Sync.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/Sync'>;
}
declare module 'twilio/lib/rest/preview/sync/service.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/sync/service'>;
}
declare module 'twilio/lib/rest/preview/sync/service/document.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/sync/service/document'>;
}
declare module 'twilio/lib/rest/preview/sync/service/document/documentPermission.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/sync/service/document/documentPermission'>;
}
declare module 'twilio/lib/rest/preview/sync/service/syncList.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/sync/service/syncList'>;
}
declare module 'twilio/lib/rest/preview/sync/service/syncList/syncListItem.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/sync/service/syncList/syncListItem'>;
}
declare module 'twilio/lib/rest/preview/sync/service/syncList/syncListPermission.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/sync/service/syncList/syncListPermission'>;
}
declare module 'twilio/lib/rest/preview/sync/service/syncMap.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/sync/service/syncMap'>;
}
declare module 'twilio/lib/rest/preview/sync/service/syncMap/syncMapItem.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/sync/service/syncMap/syncMapItem'>;
}
declare module 'twilio/lib/rest/preview/sync/service/syncMap/syncMapPermission.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/sync/service/syncMap/syncMapPermission'>;
}
declare module 'twilio/lib/rest/preview/Understand.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/Understand'>;
}
declare module 'twilio/lib/rest/preview/understand/assistant.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/understand/assistant'>;
}
declare module 'twilio/lib/rest/preview/understand/assistant/fieldType.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/understand/assistant/fieldType'>;
}
declare module 'twilio/lib/rest/preview/understand/assistant/fieldType/fieldValue.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/understand/assistant/fieldType/fieldValue'>;
}
declare module 'twilio/lib/rest/preview/understand/assistant/intent.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/understand/assistant/intent'>;
}
declare module 'twilio/lib/rest/preview/understand/assistant/intent/field.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/understand/assistant/intent/field'>;
}
declare module 'twilio/lib/rest/preview/understand/assistant/intent/sample.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/understand/assistant/intent/sample'>;
}
declare module 'twilio/lib/rest/preview/understand/assistant/modelBuild.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/understand/assistant/modelBuild'>;
}
declare module 'twilio/lib/rest/preview/understand/assistant/query.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/understand/assistant/query'>;
}
declare module 'twilio/lib/rest/preview/Wireless.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/Wireless'>;
}
declare module 'twilio/lib/rest/preview/wireless/command.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/wireless/command'>;
}
declare module 'twilio/lib/rest/preview/wireless/ratePlan.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/wireless/ratePlan'>;
}
declare module 'twilio/lib/rest/preview/wireless/sim.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/wireless/sim'>;
}
declare module 'twilio/lib/rest/preview/wireless/sim/usage.js' {
  declare module.exports: $Exports<'twilio/lib/rest/preview/wireless/sim/usage'>;
}
declare module 'twilio/lib/rest/Pricing.js' {
  declare module.exports: $Exports<'twilio/lib/rest/Pricing'>;
}
declare module 'twilio/lib/rest/pricing/V1.js' {
  declare module.exports: $Exports<'twilio/lib/rest/pricing/V1'>;
}
declare module 'twilio/lib/rest/pricing/v1/messaging.js' {
  declare module.exports: $Exports<'twilio/lib/rest/pricing/v1/messaging'>;
}
declare module 'twilio/lib/rest/pricing/v1/messaging/country.js' {
  declare module.exports: $Exports<'twilio/lib/rest/pricing/v1/messaging/country'>;
}
declare module 'twilio/lib/rest/pricing/v1/phoneNumber.js' {
  declare module.exports: $Exports<'twilio/lib/rest/pricing/v1/phoneNumber'>;
}
declare module 'twilio/lib/rest/pricing/v1/phoneNumber/country.js' {
  declare module.exports: $Exports<'twilio/lib/rest/pricing/v1/phoneNumber/country'>;
}
declare module 'twilio/lib/rest/pricing/v1/voice.js' {
  declare module.exports: $Exports<'twilio/lib/rest/pricing/v1/voice'>;
}
declare module 'twilio/lib/rest/pricing/v1/voice/country.js' {
  declare module.exports: $Exports<'twilio/lib/rest/pricing/v1/voice/country'>;
}
declare module 'twilio/lib/rest/pricing/v1/voice/number.js' {
  declare module.exports: $Exports<'twilio/lib/rest/pricing/v1/voice/number'>;
}
declare module 'twilio/lib/rest/Proxy.js' {
  declare module.exports: $Exports<'twilio/lib/rest/Proxy'>;
}
declare module 'twilio/lib/rest/proxy/V1.js' {
  declare module.exports: $Exports<'twilio/lib/rest/proxy/V1'>;
}
declare module 'twilio/lib/rest/proxy/v1/service.js' {
  declare module.exports: $Exports<'twilio/lib/rest/proxy/v1/service'>;
}
declare module 'twilio/lib/rest/proxy/v1/service/phoneNumber.js' {
  declare module.exports: $Exports<'twilio/lib/rest/proxy/v1/service/phoneNumber'>;
}
declare module 'twilio/lib/rest/proxy/v1/service/session.js' {
  declare module.exports: $Exports<'twilio/lib/rest/proxy/v1/service/session'>;
}
declare module 'twilio/lib/rest/proxy/v1/service/session/interaction.js' {
  declare module.exports: $Exports<'twilio/lib/rest/proxy/v1/service/session/interaction'>;
}
declare module 'twilio/lib/rest/proxy/v1/service/session/participant.js' {
  declare module.exports: $Exports<'twilio/lib/rest/proxy/v1/service/session/participant'>;
}
declare module 'twilio/lib/rest/proxy/v1/service/session/participant/messageInteraction.js' {
  declare module.exports: $Exports<'twilio/lib/rest/proxy/v1/service/session/participant/messageInteraction'>;
}
declare module 'twilio/lib/rest/proxy/v1/service/shortCode.js' {
  declare module.exports: $Exports<'twilio/lib/rest/proxy/v1/service/shortCode'>;
}
declare module 'twilio/lib/rest/Studio.js' {
  declare module.exports: $Exports<'twilio/lib/rest/Studio'>;
}
declare module 'twilio/lib/rest/studio/V1.js' {
  declare module.exports: $Exports<'twilio/lib/rest/studio/V1'>;
}
declare module 'twilio/lib/rest/studio/v1/flow.js' {
  declare module.exports: $Exports<'twilio/lib/rest/studio/v1/flow'>;
}
declare module 'twilio/lib/rest/studio/v1/flow/engagement.js' {
  declare module.exports: $Exports<'twilio/lib/rest/studio/v1/flow/engagement'>;
}
declare module 'twilio/lib/rest/studio/v1/flow/engagement/engagementContext.js' {
  declare module.exports: $Exports<'twilio/lib/rest/studio/v1/flow/engagement/engagementContext'>;
}
declare module 'twilio/lib/rest/studio/v1/flow/engagement/step.js' {
  declare module.exports: $Exports<'twilio/lib/rest/studio/v1/flow/engagement/step'>;
}
declare module 'twilio/lib/rest/studio/v1/flow/engagement/step/stepContext.js' {
  declare module.exports: $Exports<'twilio/lib/rest/studio/v1/flow/engagement/step/stepContext'>;
}
declare module 'twilio/lib/rest/Sync.js' {
  declare module.exports: $Exports<'twilio/lib/rest/Sync'>;
}
declare module 'twilio/lib/rest/sync/V1.js' {
  declare module.exports: $Exports<'twilio/lib/rest/sync/V1'>;
}
declare module 'twilio/lib/rest/sync/v1/service.js' {
  declare module.exports: $Exports<'twilio/lib/rest/sync/v1/service'>;
}
declare module 'twilio/lib/rest/sync/v1/service/document.js' {
  declare module.exports: $Exports<'twilio/lib/rest/sync/v1/service/document'>;
}
declare module 'twilio/lib/rest/sync/v1/service/document/documentPermission.js' {
  declare module.exports: $Exports<'twilio/lib/rest/sync/v1/service/document/documentPermission'>;
}
declare module 'twilio/lib/rest/sync/v1/service/syncList.js' {
  declare module.exports: $Exports<'twilio/lib/rest/sync/v1/service/syncList'>;
}
declare module 'twilio/lib/rest/sync/v1/service/syncList/syncListItem.js' {
  declare module.exports: $Exports<'twilio/lib/rest/sync/v1/service/syncList/syncListItem'>;
}
declare module 'twilio/lib/rest/sync/v1/service/syncList/syncListPermission.js' {
  declare module.exports: $Exports<'twilio/lib/rest/sync/v1/service/syncList/syncListPermission'>;
}
declare module 'twilio/lib/rest/sync/v1/service/syncMap.js' {
  declare module.exports: $Exports<'twilio/lib/rest/sync/v1/service/syncMap'>;
}
declare module 'twilio/lib/rest/sync/v1/service/syncMap/syncMapItem.js' {
  declare module.exports: $Exports<'twilio/lib/rest/sync/v1/service/syncMap/syncMapItem'>;
}
declare module 'twilio/lib/rest/sync/v1/service/syncMap/syncMapPermission.js' {
  declare module.exports: $Exports<'twilio/lib/rest/sync/v1/service/syncMap/syncMapPermission'>;
}
declare module 'twilio/lib/rest/sync/v1/service/syncStream.js' {
  declare module.exports: $Exports<'twilio/lib/rest/sync/v1/service/syncStream'>;
}
declare module 'twilio/lib/rest/sync/v1/service/syncStream/streamMessage.js' {
  declare module.exports: $Exports<'twilio/lib/rest/sync/v1/service/syncStream/streamMessage'>;
}
declare module 'twilio/lib/rest/Taskrouter.js' {
  declare module.exports: $Exports<'twilio/lib/rest/Taskrouter'>;
}
declare module 'twilio/lib/rest/taskrouter/V1.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/V1'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/activity.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/activity'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/event.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/event'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/task.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/task'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/task/reservation.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/task/reservation'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/taskChannel.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/taskChannel'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/taskQueue.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/taskQueue'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/taskQueue/taskQueueCumulativeStatistics.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/taskQueue/taskQueueCumulativeStatistics'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/taskQueue/taskQueueRealTimeStatistics.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/taskQueue/taskQueueRealTimeStatistics'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/taskQueue/taskQueuesStatistics.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/taskQueue/taskQueuesStatistics'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/taskQueue/taskQueueStatistics.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/taskQueue/taskQueueStatistics'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/worker.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/worker'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/worker/reservation.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/worker/reservation'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/worker/workerChannel.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/worker/workerChannel'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/worker/workersCumulativeStatistics.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/worker/workersCumulativeStatistics'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/worker/workersRealTimeStatistics.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/worker/workersRealTimeStatistics'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/worker/workersStatistics.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/worker/workersStatistics'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/worker/workerStatistics.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/worker/workerStatistics'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/workflow.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/workflow'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/workflow/workflowCumulativeStatistics.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/workflow/workflowCumulativeStatistics'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/workflow/workflowRealTimeStatistics.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/workflow/workflowRealTimeStatistics'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/workflow/workflowStatistics.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/workflow/workflowStatistics'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/workspaceCumulativeStatistics.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/workspaceCumulativeStatistics'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/workspaceRealTimeStatistics.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/workspaceRealTimeStatistics'>;
}
declare module 'twilio/lib/rest/taskrouter/v1/workspace/workspaceStatistics.js' {
  declare module.exports: $Exports<'twilio/lib/rest/taskrouter/v1/workspace/workspaceStatistics'>;
}
declare module 'twilio/lib/rest/Trunking.js' {
  declare module.exports: $Exports<'twilio/lib/rest/Trunking'>;
}
declare module 'twilio/lib/rest/trunking/V1.js' {
  declare module.exports: $Exports<'twilio/lib/rest/trunking/V1'>;
}
declare module 'twilio/lib/rest/trunking/v1/trunk.js' {
  declare module.exports: $Exports<'twilio/lib/rest/trunking/v1/trunk'>;
}
declare module 'twilio/lib/rest/trunking/v1/trunk/credentialList.js' {
  declare module.exports: $Exports<'twilio/lib/rest/trunking/v1/trunk/credentialList'>;
}
declare module 'twilio/lib/rest/trunking/v1/trunk/ipAccessControlList.js' {
  declare module.exports: $Exports<'twilio/lib/rest/trunking/v1/trunk/ipAccessControlList'>;
}
declare module 'twilio/lib/rest/trunking/v1/trunk/originationUrl.js' {
  declare module.exports: $Exports<'twilio/lib/rest/trunking/v1/trunk/originationUrl'>;
}
declare module 'twilio/lib/rest/trunking/v1/trunk/phoneNumber.js' {
  declare module.exports: $Exports<'twilio/lib/rest/trunking/v1/trunk/phoneNumber'>;
}
declare module 'twilio/lib/rest/Twilio.js' {
  declare module.exports: $Exports<'twilio/lib/rest/Twilio'>;
}
declare module 'twilio/lib/rest/Video.js' {
  declare module.exports: $Exports<'twilio/lib/rest/Video'>;
}
declare module 'twilio/lib/rest/video/V1.js' {
  declare module.exports: $Exports<'twilio/lib/rest/video/V1'>;
}
declare module 'twilio/lib/rest/video/v1/composition.js' {
  declare module.exports: $Exports<'twilio/lib/rest/video/v1/composition'>;
}
declare module 'twilio/lib/rest/video/v1/recording.js' {
  declare module.exports: $Exports<'twilio/lib/rest/video/v1/recording'>;
}
declare module 'twilio/lib/rest/video/v1/room.js' {
  declare module.exports: $Exports<'twilio/lib/rest/video/v1/room'>;
}
declare module 'twilio/lib/rest/video/v1/room/recording.js' {
  declare module.exports: $Exports<'twilio/lib/rest/video/v1/room/recording'>;
}
declare module 'twilio/lib/rest/video/v1/room/roomParticipant.js' {
  declare module.exports: $Exports<'twilio/lib/rest/video/v1/room/roomParticipant'>;
}
declare module 'twilio/lib/rest/video/v1/room/roomParticipant/roomParticipantPublishedTrack.js' {
  declare module.exports: $Exports<'twilio/lib/rest/video/v1/room/roomParticipant/roomParticipantPublishedTrack'>;
}
declare module 'twilio/lib/rest/video/v1/room/roomParticipant/roomParticipantSubscribedTrack.js' {
  declare module.exports: $Exports<'twilio/lib/rest/video/v1/room/roomParticipant/roomParticipantSubscribedTrack'>;
}
declare module 'twilio/lib/rest/Wireless.js' {
  declare module.exports: $Exports<'twilio/lib/rest/Wireless'>;
}
declare module 'twilio/lib/rest/wireless/V1.js' {
  declare module.exports: $Exports<'twilio/lib/rest/wireless/V1'>;
}
declare module 'twilio/lib/rest/wireless/v1/command.js' {
  declare module.exports: $Exports<'twilio/lib/rest/wireless/v1/command'>;
}
declare module 'twilio/lib/rest/wireless/v1/ratePlan.js' {
  declare module.exports: $Exports<'twilio/lib/rest/wireless/v1/ratePlan'>;
}
declare module 'twilio/lib/rest/wireless/v1/sim.js' {
  declare module.exports: $Exports<'twilio/lib/rest/wireless/v1/sim'>;
}
declare module 'twilio/lib/rest/wireless/v1/sim/dataSession.js' {
  declare module.exports: $Exports<'twilio/lib/rest/wireless/v1/sim/dataSession'>;
}
declare module 'twilio/lib/rest/wireless/v1/sim/usageRecord.js' {
  declare module.exports: $Exports<'twilio/lib/rest/wireless/v1/sim/usageRecord'>;
}
declare module 'twilio/lib/twiml/FaxResponse.js' {
  declare module.exports: $Exports<'twilio/lib/twiml/FaxResponse'>;
}
declare module 'twilio/lib/twiml/MessagingResponse.js' {
  declare module.exports: $Exports<'twilio/lib/twiml/MessagingResponse'>;
}
declare module 'twilio/lib/twiml/VoiceResponse.js' {
  declare module.exports: $Exports<'twilio/lib/twiml/VoiceResponse'>;
}
declare module 'twilio/lib/webhooks/webhooks.js' {
  declare module.exports: $Exports<'twilio/lib/webhooks/webhooks'>;
}
