// flow-typed signature: df14d8f6bf5a1eb4ff46b97da16a8c28
// flow-typed version: <<STUB>>/uppy_v0.21.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uppy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uppy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uppy/bin/build-css' {
  declare module.exports: any;
}

declare module 'uppy/bin/build-js' {
  declare module.exports: any;
}

declare module 'uppy/bin/disc' {
  declare module.exports: any;
}

declare module 'uppy/bin/gzip' {
  declare module.exports: any;
}

declare module 'uppy/dist/uppy' {
  declare module.exports: any;
}

declare module 'uppy/dist/uppy.min' {
  declare module.exports: any;
}

declare module 'uppy/examples/aws-presigned-url/main' {
  declare module.exports: any;
}

declare module 'uppy/examples/aws-presigned-url/serve' {
  declare module.exports: any;
}

declare module 'uppy/examples/aws-uppy-server/aliasify' {
  declare module.exports: any;
}

declare module 'uppy/examples/aws-uppy-server/main' {
  declare module.exports: any;
}

declare module 'uppy/examples/aws-uppy-server/server' {
  declare module.exports: any;
}

declare module 'uppy/examples/bundled-example/bundle' {
  declare module.exports: any;
}

declare module 'uppy/examples/bundled-example/main' {
  declare module.exports: any;
}

declare module 'uppy/examples/bundled-example/sw' {
  declare module.exports: any;
}

declare module 'uppy/examples/multiple-instances/aliasify' {
  declare module.exports: any;
}

declare module 'uppy/examples/multiple-instances/main' {
  declare module.exports: any;
}

declare module 'uppy/examples/react-example/aliasify' {
  declare module.exports: any;
}

declare module 'uppy/examples/react-example/App' {
  declare module.exports: any;
}

declare module 'uppy/examples/react-example/main' {
  declare module.exports: any;
}

declare module 'uppy/examples/redux/aliasify' {
  declare module.exports: any;
}

declare module 'uppy/examples/redux/main' {
  declare module.exports: any;
}

declare module 'uppy/lib/core' {
  declare module.exports: any;
}

declare module 'uppy/lib/core/Core' {
  declare module.exports: any;
}

declare module 'uppy/lib/core/Core.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/core/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/core/index.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/core/Translator' {
  declare module.exports: any;
}

declare module 'uppy/lib/core/Translator.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/core/UppySocket' {
  declare module.exports: any;
}

declare module 'uppy/lib/core/UppySocket.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/core/Utils' {
  declare module.exports: any;
}

declare module 'uppy/lib/core/Utils.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/generic-provider-views/AuthView' {
  declare module.exports: any;
}

declare module 'uppy/lib/generic-provider-views/Breadcrumb' {
  declare module.exports: any;
}

declare module 'uppy/lib/generic-provider-views/Breadcrumbs' {
  declare module.exports: any;
}

declare module 'uppy/lib/generic-provider-views/Browser' {
  declare module.exports: any;
}

declare module 'uppy/lib/generic-provider-views/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/generic-provider-views/Loader' {
  declare module.exports: any;
}

declare module 'uppy/lib/generic-provider-views/Table' {
  declare module.exports: any;
}

declare module 'uppy/lib/generic-provider-views/TableRow' {
  declare module.exports: any;
}

declare module 'uppy/lib/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/locales/en_US' {
  declare module.exports: any;
}

declare module 'uppy/lib/locales/it_IT' {
  declare module.exports: any;
}

declare module 'uppy/lib/locales/nb_NO' {
  declare module.exports: any;
}

declare module 'uppy/lib/locales/pt_BR' {
  declare module.exports: any;
}

declare module 'uppy/lib/locales/ru_RU' {
  declare module.exports: any;
}

declare module 'uppy/lib/locales/tr_TR' {
  declare module.exports: any;
}

declare module 'uppy/lib/locales/zh_CN' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/AwsS3/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dashboard/ActionBrowseTagline' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dashboard/Dashboard' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dashboard/FileCard' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dashboard/FileItem' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dashboard/FileItemProgress' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dashboard/FileList' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dashboard/getFileTypeIcon' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dashboard/icons' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dashboard/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dashboard/Tabs' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dashboard/UploadBtn' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/DragDrop/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dropbox/icons' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dropbox/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dummy' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/FileInput' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/GoldenRetriever/cleanup' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/GoldenRetriever/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/GoldenRetriever/IndexedDBStore' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/GoldenRetriever/MetaDataStore' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/GoldenRetriever/ServiceWorker' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/GoldenRetriever/ServiceWorkerStore' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/GoogleDrive/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Informer' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Instagram/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/MagicLog' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/MetaData' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Plugin' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Plugin.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/ProgressBar' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Redux' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Redux.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/ReduxDevTools' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/RestoreFiles/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/StatusBar/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/StatusBar/StatusBar' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Transloadit/Client' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Transloadit/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Transloadit/index.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Transloadit/Socket' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Tus' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Tus10' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/CameraIcon' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/CameraScreen' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/PermissionsScreen' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/RecordButton' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/RecordStartIcon' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/RecordStopIcon' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/SnapshotButton' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/supportsMediaRecorder' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/supportsMediaRecorder.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/WebcamIcon' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/XHRUpload' {
  declare module.exports: any;
}

declare module 'uppy/lib/Provider' {
  declare module.exports: any;
}

declare module 'uppy/lib/react/Dashboard' {
  declare module.exports: any;
}

declare module 'uppy/lib/react/DashboardModal' {
  declare module.exports: any;
}

declare module 'uppy/lib/react/DragDrop' {
  declare module.exports: any;
}

declare module 'uppy/lib/react/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/react/ProgressBar' {
  declare module.exports: any;
}

declare module 'uppy/lib/react/StatusBar' {
  declare module.exports: any;
}

declare module 'uppy/lib/react/Wrapper' {
  declare module.exports: any;
}

declare module 'uppy/lib/store/DefaultStore' {
  declare module.exports: any;
}

declare module 'uppy/lib/store/DefaultStore.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/store/ReduxStore' {
  declare module.exports: any;
}

declare module 'uppy/lib/store/ReduxStore.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/vendor/file-type/index' {
  declare module.exports: any;
}

declare module 'uppy/src/core/Core' {
  declare module.exports: any;
}

declare module 'uppy/src/core/Core.test' {
  declare module.exports: any;
}

declare module 'uppy/src/core/index' {
  declare module.exports: any;
}

declare module 'uppy/src/core/index.test' {
  declare module.exports: any;
}

declare module 'uppy/src/core/Translator' {
  declare module.exports: any;
}

declare module 'uppy/src/core/Translator.test' {
  declare module.exports: any;
}

declare module 'uppy/src/core/UppySocket' {
  declare module.exports: any;
}

declare module 'uppy/src/core/UppySocket.test' {
  declare module.exports: any;
}

declare module 'uppy/src/core/Utils' {
  declare module.exports: any;
}

declare module 'uppy/src/core/Utils.test' {
  declare module.exports: any;
}

declare module 'uppy/src/generic-provider-views/AuthView' {
  declare module.exports: any;
}

declare module 'uppy/src/generic-provider-views/Breadcrumb' {
  declare module.exports: any;
}

declare module 'uppy/src/generic-provider-views/Breadcrumbs' {
  declare module.exports: any;
}

declare module 'uppy/src/generic-provider-views/Browser' {
  declare module.exports: any;
}

declare module 'uppy/src/generic-provider-views/index' {
  declare module.exports: any;
}

declare module 'uppy/src/generic-provider-views/Loader' {
  declare module.exports: any;
}

declare module 'uppy/src/generic-provider-views/Table' {
  declare module.exports: any;
}

declare module 'uppy/src/generic-provider-views/TableRow' {
  declare module.exports: any;
}

declare module 'uppy/src/index' {
  declare module.exports: any;
}

declare module 'uppy/src/locales/en_US' {
  declare module.exports: any;
}

declare module 'uppy/src/locales/it_IT' {
  declare module.exports: any;
}

declare module 'uppy/src/locales/nb_NO' {
  declare module.exports: any;
}

declare module 'uppy/src/locales/pt_BR' {
  declare module.exports: any;
}

declare module 'uppy/src/locales/ru_RU' {
  declare module.exports: any;
}

declare module 'uppy/src/locales/tr_TR' {
  declare module.exports: any;
}

declare module 'uppy/src/locales/zh_CN' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/AwsS3/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dashboard/ActionBrowseTagline' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dashboard/Dashboard' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dashboard/FileCard' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dashboard/FileItem' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dashboard/FileItemProgress' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dashboard/FileList' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dashboard/getFileTypeIcon' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dashboard/icons' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dashboard/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dashboard/Tabs' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dashboard/UploadBtn' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/DragDrop/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dropbox/icons' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dropbox/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dummy' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/FileInput' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/GoldenRetriever/cleanup' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/GoldenRetriever/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/GoldenRetriever/IndexedDBStore' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/GoldenRetriever/MetaDataStore' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/GoldenRetriever/ServiceWorker' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/GoldenRetriever/ServiceWorkerStore' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/GoogleDrive/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Informer' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Instagram/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/MagicLog' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/MetaData' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Plugin' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Plugin.test' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/ProgressBar' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Redux' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Redux.test' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/ReduxDevTools' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/RestoreFiles/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/StatusBar/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/StatusBar/StatusBar' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Transloadit/Client' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Transloadit/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Transloadit/index.test' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Transloadit/Socket' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Tus' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Tus10' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/CameraIcon' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/CameraScreen' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/PermissionsScreen' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/RecordButton' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/RecordStartIcon' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/RecordStopIcon' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/SnapshotButton' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/supportsMediaRecorder' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/supportsMediaRecorder.test' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/WebcamIcon' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/XHRUpload' {
  declare module.exports: any;
}

declare module 'uppy/src/Provider' {
  declare module.exports: any;
}

declare module 'uppy/src/react/Dashboard' {
  declare module.exports: any;
}

declare module 'uppy/src/react/DashboardModal' {
  declare module.exports: any;
}

declare module 'uppy/src/react/DragDrop' {
  declare module.exports: any;
}

declare module 'uppy/src/react/index' {
  declare module.exports: any;
}

declare module 'uppy/src/react/ProgressBar' {
  declare module.exports: any;
}

declare module 'uppy/src/react/StatusBar' {
  declare module.exports: any;
}

declare module 'uppy/src/react/Wrapper' {
  declare module.exports: any;
}

declare module 'uppy/src/store/DefaultStore' {
  declare module.exports: any;
}

declare module 'uppy/src/store/DefaultStore.test' {
  declare module.exports: any;
}

declare module 'uppy/src/store/ReduxStore' {
  declare module.exports: any;
}

declare module 'uppy/src/store/ReduxStore.test' {
  declare module.exports: any;
}

declare module 'uppy/src/vendor/file-type/index' {
  declare module.exports: any;
}

declare module 'uppy/test/acceptance/dragdrop.spec' {
  declare module.exports: any;
}

declare module 'uppy/test/acceptance/dummy.spec' {
  declare module.exports: any;
}

declare module 'uppy/test/acceptance/fallback.spec' {
  declare module.exports: any;
}

declare module 'uppy/test/acceptance/i18n.spec' {
  declare module.exports: any;
}

declare module 'uppy/test/acceptance/index' {
  declare module.exports: any;
}

declare module 'uppy/test/acceptance/multipart.spec' {
  declare module.exports: any;
}

declare module 'uppy/test/acceptance/saucelabs-dummy.spec' {
  declare module.exports: any;
}

declare module 'uppy/test/acceptance/tools' {
  declare module.exports: any;
}

declare module 'uppy/test/endtoend/dist/bundle' {
  declare module.exports: any;
}

declare module 'uppy/test/endtoend/specs/uppy.test' {
  declare module.exports: any;
}

declare module 'uppy/test/endtoend/src/main' {
  declare module.exports: any;
}

declare module 'uppy/test/endtoend/wdio.local.conf' {
  declare module.exports: any;
}

declare module 'uppy/test/endtoend/wdio.remote.conf' {
  declare module.exports: any;
}

declare module 'uppy/test/mocks/acquirerPlugin1' {
  declare module.exports: any;
}

declare module 'uppy/test/mocks/acquirerPlugin2' {
  declare module.exports: any;
}

declare module 'uppy/test/mocks/invalidPlugin' {
  declare module.exports: any;
}

declare module 'uppy/test/mocks/invalidPluginWithoutId' {
  declare module.exports: any;
}

declare module 'uppy/test/mocks/invalidPluginWithoutType' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uppy/bin/build-css.js' {
  declare module.exports: $Exports<'uppy/bin/build-css'>;
}
declare module 'uppy/bin/build-js.js' {
  declare module.exports: $Exports<'uppy/bin/build-js'>;
}
declare module 'uppy/bin/disc.js' {
  declare module.exports: $Exports<'uppy/bin/disc'>;
}
declare module 'uppy/bin/gzip.js' {
  declare module.exports: $Exports<'uppy/bin/gzip'>;
}
declare module 'uppy/dist/uppy.js' {
  declare module.exports: $Exports<'uppy/dist/uppy'>;
}
declare module 'uppy/dist/uppy.min.js' {
  declare module.exports: $Exports<'uppy/dist/uppy.min'>;
}
declare module 'uppy/examples/aws-presigned-url/main.js' {
  declare module.exports: $Exports<'uppy/examples/aws-presigned-url/main'>;
}
declare module 'uppy/examples/aws-presigned-url/serve.js' {
  declare module.exports: $Exports<'uppy/examples/aws-presigned-url/serve'>;
}
declare module 'uppy/examples/aws-uppy-server/aliasify.js' {
  declare module.exports: $Exports<'uppy/examples/aws-uppy-server/aliasify'>;
}
declare module 'uppy/examples/aws-uppy-server/main.js' {
  declare module.exports: $Exports<'uppy/examples/aws-uppy-server/main'>;
}
declare module 'uppy/examples/aws-uppy-server/server.js' {
  declare module.exports: $Exports<'uppy/examples/aws-uppy-server/server'>;
}
declare module 'uppy/examples/bundled-example/bundle.js' {
  declare module.exports: $Exports<'uppy/examples/bundled-example/bundle'>;
}
declare module 'uppy/examples/bundled-example/main.js' {
  declare module.exports: $Exports<'uppy/examples/bundled-example/main'>;
}
declare module 'uppy/examples/bundled-example/sw.js' {
  declare module.exports: $Exports<'uppy/examples/bundled-example/sw'>;
}
declare module 'uppy/examples/multiple-instances/aliasify.js' {
  declare module.exports: $Exports<'uppy/examples/multiple-instances/aliasify'>;
}
declare module 'uppy/examples/multiple-instances/main.js' {
  declare module.exports: $Exports<'uppy/examples/multiple-instances/main'>;
}
declare module 'uppy/examples/react-example/aliasify.js' {
  declare module.exports: $Exports<'uppy/examples/react-example/aliasify'>;
}
declare module 'uppy/examples/react-example/App.js' {
  declare module.exports: $Exports<'uppy/examples/react-example/App'>;
}
declare module 'uppy/examples/react-example/main.js' {
  declare module.exports: $Exports<'uppy/examples/react-example/main'>;
}
declare module 'uppy/examples/redux/aliasify.js' {
  declare module.exports: $Exports<'uppy/examples/redux/aliasify'>;
}
declare module 'uppy/examples/redux/main.js' {
  declare module.exports: $Exports<'uppy/examples/redux/main'>;
}
declare module 'uppy/lib/core/Core.js' {
  declare module.exports: $Exports<'uppy/lib/core/Core'>;
}
declare module 'uppy/lib/core/Core.test.js' {
  declare module.exports: $Exports<'uppy/lib/core/Core.test'>;
}
declare module 'uppy/lib/core/index.js' {
  declare module.exports: $Exports<'uppy/lib/core/index'>;
}
declare module 'uppy/lib/core/index.test.js' {
  declare module.exports: $Exports<'uppy/lib/core/index.test'>;
}
declare module 'uppy/lib/core/Translator.js' {
  declare module.exports: $Exports<'uppy/lib/core/Translator'>;
}
declare module 'uppy/lib/core/Translator.test.js' {
  declare module.exports: $Exports<'uppy/lib/core/Translator.test'>;
}
declare module 'uppy/lib/core/UppySocket.js' {
  declare module.exports: $Exports<'uppy/lib/core/UppySocket'>;
}
declare module 'uppy/lib/core/UppySocket.test.js' {
  declare module.exports: $Exports<'uppy/lib/core/UppySocket.test'>;
}
declare module 'uppy/lib/core/Utils.js' {
  declare module.exports: $Exports<'uppy/lib/core/Utils'>;
}
declare module 'uppy/lib/core/Utils.test.js' {
  declare module.exports: $Exports<'uppy/lib/core/Utils.test'>;
}
declare module 'uppy/lib/generic-provider-views/AuthView.js' {
  declare module.exports: $Exports<'uppy/lib/generic-provider-views/AuthView'>;
}
declare module 'uppy/lib/generic-provider-views/Breadcrumb.js' {
  declare module.exports: $Exports<'uppy/lib/generic-provider-views/Breadcrumb'>;
}
declare module 'uppy/lib/generic-provider-views/Breadcrumbs.js' {
  declare module.exports: $Exports<'uppy/lib/generic-provider-views/Breadcrumbs'>;
}
declare module 'uppy/lib/generic-provider-views/Browser.js' {
  declare module.exports: $Exports<'uppy/lib/generic-provider-views/Browser'>;
}
declare module 'uppy/lib/generic-provider-views/index.js' {
  declare module.exports: $Exports<'uppy/lib/generic-provider-views/index'>;
}
declare module 'uppy/lib/generic-provider-views/Loader.js' {
  declare module.exports: $Exports<'uppy/lib/generic-provider-views/Loader'>;
}
declare module 'uppy/lib/generic-provider-views/Table.js' {
  declare module.exports: $Exports<'uppy/lib/generic-provider-views/Table'>;
}
declare module 'uppy/lib/generic-provider-views/TableRow.js' {
  declare module.exports: $Exports<'uppy/lib/generic-provider-views/TableRow'>;
}
declare module 'uppy/lib/index.js' {
  declare module.exports: $Exports<'uppy/lib/index'>;
}
declare module 'uppy/lib/locales/en_US.js' {
  declare module.exports: $Exports<'uppy/lib/locales/en_US'>;
}
declare module 'uppy/lib/locales/it_IT.js' {
  declare module.exports: $Exports<'uppy/lib/locales/it_IT'>;
}
declare module 'uppy/lib/locales/nb_NO.js' {
  declare module.exports: $Exports<'uppy/lib/locales/nb_NO'>;
}
declare module 'uppy/lib/locales/pt_BR.js' {
  declare module.exports: $Exports<'uppy/lib/locales/pt_BR'>;
}
declare module 'uppy/lib/locales/ru_RU.js' {
  declare module.exports: $Exports<'uppy/lib/locales/ru_RU'>;
}
declare module 'uppy/lib/locales/tr_TR.js' {
  declare module.exports: $Exports<'uppy/lib/locales/tr_TR'>;
}
declare module 'uppy/lib/locales/zh_CN.js' {
  declare module.exports: $Exports<'uppy/lib/locales/zh_CN'>;
}
declare module 'uppy/lib/plugins/AwsS3/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/AwsS3/index'>;
}
declare module 'uppy/lib/plugins/Dashboard/ActionBrowseTagline.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dashboard/ActionBrowseTagline'>;
}
declare module 'uppy/lib/plugins/Dashboard/Dashboard.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dashboard/Dashboard'>;
}
declare module 'uppy/lib/plugins/Dashboard/FileCard.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dashboard/FileCard'>;
}
declare module 'uppy/lib/plugins/Dashboard/FileItem.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dashboard/FileItem'>;
}
declare module 'uppy/lib/plugins/Dashboard/FileItemProgress.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dashboard/FileItemProgress'>;
}
declare module 'uppy/lib/plugins/Dashboard/FileList.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dashboard/FileList'>;
}
declare module 'uppy/lib/plugins/Dashboard/getFileTypeIcon.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dashboard/getFileTypeIcon'>;
}
declare module 'uppy/lib/plugins/Dashboard/icons.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dashboard/icons'>;
}
declare module 'uppy/lib/plugins/Dashboard/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dashboard/index'>;
}
declare module 'uppy/lib/plugins/Dashboard/Tabs.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dashboard/Tabs'>;
}
declare module 'uppy/lib/plugins/Dashboard/UploadBtn.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dashboard/UploadBtn'>;
}
declare module 'uppy/lib/plugins/DragDrop/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/DragDrop/index'>;
}
declare module 'uppy/lib/plugins/Dropbox/icons.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dropbox/icons'>;
}
declare module 'uppy/lib/plugins/Dropbox/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dropbox/index'>;
}
declare module 'uppy/lib/plugins/Dummy.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dummy'>;
}
declare module 'uppy/lib/plugins/FileInput.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/FileInput'>;
}
declare module 'uppy/lib/plugins/GoldenRetriever/cleanup.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/GoldenRetriever/cleanup'>;
}
declare module 'uppy/lib/plugins/GoldenRetriever/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/GoldenRetriever/index'>;
}
declare module 'uppy/lib/plugins/GoldenRetriever/IndexedDBStore.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/GoldenRetriever/IndexedDBStore'>;
}
declare module 'uppy/lib/plugins/GoldenRetriever/MetaDataStore.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/GoldenRetriever/MetaDataStore'>;
}
declare module 'uppy/lib/plugins/GoldenRetriever/ServiceWorker.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/GoldenRetriever/ServiceWorker'>;
}
declare module 'uppy/lib/plugins/GoldenRetriever/ServiceWorkerStore.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/GoldenRetriever/ServiceWorkerStore'>;
}
declare module 'uppy/lib/plugins/GoogleDrive/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/GoogleDrive/index'>;
}
declare module 'uppy/lib/plugins/Informer.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Informer'>;
}
declare module 'uppy/lib/plugins/Instagram/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Instagram/index'>;
}
declare module 'uppy/lib/plugins/MagicLog.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/MagicLog'>;
}
declare module 'uppy/lib/plugins/MetaData.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/MetaData'>;
}
declare module 'uppy/lib/plugins/Plugin.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Plugin'>;
}
declare module 'uppy/lib/plugins/Plugin.test.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Plugin.test'>;
}
declare module 'uppy/lib/plugins/ProgressBar.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/ProgressBar'>;
}
declare module 'uppy/lib/plugins/Redux.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Redux'>;
}
declare module 'uppy/lib/plugins/Redux.test.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Redux.test'>;
}
declare module 'uppy/lib/plugins/ReduxDevTools.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/ReduxDevTools'>;
}
declare module 'uppy/lib/plugins/RestoreFiles/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/RestoreFiles/index'>;
}
declare module 'uppy/lib/plugins/StatusBar/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/StatusBar/index'>;
}
declare module 'uppy/lib/plugins/StatusBar/StatusBar.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/StatusBar/StatusBar'>;
}
declare module 'uppy/lib/plugins/Transloadit/Client.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Transloadit/Client'>;
}
declare module 'uppy/lib/plugins/Transloadit/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Transloadit/index'>;
}
declare module 'uppy/lib/plugins/Transloadit/index.test.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Transloadit/index.test'>;
}
declare module 'uppy/lib/plugins/Transloadit/Socket.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Transloadit/Socket'>;
}
declare module 'uppy/lib/plugins/Tus.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Tus'>;
}
declare module 'uppy/lib/plugins/Tus10.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Tus10'>;
}
declare module 'uppy/lib/plugins/Webcam/CameraIcon.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/CameraIcon'>;
}
declare module 'uppy/lib/plugins/Webcam/CameraScreen.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/CameraScreen'>;
}
declare module 'uppy/lib/plugins/Webcam/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/index'>;
}
declare module 'uppy/lib/plugins/Webcam/PermissionsScreen.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/PermissionsScreen'>;
}
declare module 'uppy/lib/plugins/Webcam/RecordButton.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/RecordButton'>;
}
declare module 'uppy/lib/plugins/Webcam/RecordStartIcon.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/RecordStartIcon'>;
}
declare module 'uppy/lib/plugins/Webcam/RecordStopIcon.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/RecordStopIcon'>;
}
declare module 'uppy/lib/plugins/Webcam/SnapshotButton.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/SnapshotButton'>;
}
declare module 'uppy/lib/plugins/Webcam/supportsMediaRecorder.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/supportsMediaRecorder'>;
}
declare module 'uppy/lib/plugins/Webcam/supportsMediaRecorder.test.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/supportsMediaRecorder.test'>;
}
declare module 'uppy/lib/plugins/Webcam/WebcamIcon.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/WebcamIcon'>;
}
declare module 'uppy/lib/plugins/XHRUpload.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/XHRUpload'>;
}
declare module 'uppy/lib/Provider.js' {
  declare module.exports: $Exports<'uppy/lib/Provider'>;
}
declare module 'uppy/lib/react/Dashboard.js' {
  declare module.exports: $Exports<'uppy/lib/react/Dashboard'>;
}
declare module 'uppy/lib/react/DashboardModal.js' {
  declare module.exports: $Exports<'uppy/lib/react/DashboardModal'>;
}
declare module 'uppy/lib/react/DragDrop.js' {
  declare module.exports: $Exports<'uppy/lib/react/DragDrop'>;
}
declare module 'uppy/lib/react/index.js' {
  declare module.exports: $Exports<'uppy/lib/react/index'>;
}
declare module 'uppy/lib/react/ProgressBar.js' {
  declare module.exports: $Exports<'uppy/lib/react/ProgressBar'>;
}
declare module 'uppy/lib/react/StatusBar.js' {
  declare module.exports: $Exports<'uppy/lib/react/StatusBar'>;
}
declare module 'uppy/lib/react/Wrapper.js' {
  declare module.exports: $Exports<'uppy/lib/react/Wrapper'>;
}
declare module 'uppy/lib/store/DefaultStore.js' {
  declare module.exports: $Exports<'uppy/lib/store/DefaultStore'>;
}
declare module 'uppy/lib/store/DefaultStore.test.js' {
  declare module.exports: $Exports<'uppy/lib/store/DefaultStore.test'>;
}
declare module 'uppy/lib/store/ReduxStore.js' {
  declare module.exports: $Exports<'uppy/lib/store/ReduxStore'>;
}
declare module 'uppy/lib/store/ReduxStore.test.js' {
  declare module.exports: $Exports<'uppy/lib/store/ReduxStore.test'>;
}
declare module 'uppy/lib/vendor/file-type/index.js' {
  declare module.exports: $Exports<'uppy/lib/vendor/file-type/index'>;
}
declare module 'uppy/src/core/Core.js' {
  declare module.exports: $Exports<'uppy/src/core/Core'>;
}
declare module 'uppy/src/core/Core.test.js' {
  declare module.exports: $Exports<'uppy/src/core/Core.test'>;
}
declare module 'uppy/src/core/index.js' {
  declare module.exports: $Exports<'uppy/src/core/index'>;
}
declare module 'uppy/src/core/index.test.js' {
  declare module.exports: $Exports<'uppy/src/core/index.test'>;
}
declare module 'uppy/src/core/Translator.js' {
  declare module.exports: $Exports<'uppy/src/core/Translator'>;
}
declare module 'uppy/src/core/Translator.test.js' {
  declare module.exports: $Exports<'uppy/src/core/Translator.test'>;
}
declare module 'uppy/src/core/UppySocket.js' {
  declare module.exports: $Exports<'uppy/src/core/UppySocket'>;
}
declare module 'uppy/src/core/UppySocket.test.js' {
  declare module.exports: $Exports<'uppy/src/core/UppySocket.test'>;
}
declare module 'uppy/src/core/Utils.js' {
  declare module.exports: $Exports<'uppy/src/core/Utils'>;
}
declare module 'uppy/src/core/Utils.test.js' {
  declare module.exports: $Exports<'uppy/src/core/Utils.test'>;
}
declare module 'uppy/src/generic-provider-views/AuthView.js' {
  declare module.exports: $Exports<'uppy/src/generic-provider-views/AuthView'>;
}
declare module 'uppy/src/generic-provider-views/Breadcrumb.js' {
  declare module.exports: $Exports<'uppy/src/generic-provider-views/Breadcrumb'>;
}
declare module 'uppy/src/generic-provider-views/Breadcrumbs.js' {
  declare module.exports: $Exports<'uppy/src/generic-provider-views/Breadcrumbs'>;
}
declare module 'uppy/src/generic-provider-views/Browser.js' {
  declare module.exports: $Exports<'uppy/src/generic-provider-views/Browser'>;
}
declare module 'uppy/src/generic-provider-views/index.js' {
  declare module.exports: $Exports<'uppy/src/generic-provider-views/index'>;
}
declare module 'uppy/src/generic-provider-views/Loader.js' {
  declare module.exports: $Exports<'uppy/src/generic-provider-views/Loader'>;
}
declare module 'uppy/src/generic-provider-views/Table.js' {
  declare module.exports: $Exports<'uppy/src/generic-provider-views/Table'>;
}
declare module 'uppy/src/generic-provider-views/TableRow.js' {
  declare module.exports: $Exports<'uppy/src/generic-provider-views/TableRow'>;
}
declare module 'uppy/src/index.js' {
  declare module.exports: $Exports<'uppy/src/index'>;
}
declare module 'uppy/src/locales/en_US.js' {
  declare module.exports: $Exports<'uppy/src/locales/en_US'>;
}
declare module 'uppy/src/locales/it_IT.js' {
  declare module.exports: $Exports<'uppy/src/locales/it_IT'>;
}
declare module 'uppy/src/locales/nb_NO.js' {
  declare module.exports: $Exports<'uppy/src/locales/nb_NO'>;
}
declare module 'uppy/src/locales/pt_BR.js' {
  declare module.exports: $Exports<'uppy/src/locales/pt_BR'>;
}
declare module 'uppy/src/locales/ru_RU.js' {
  declare module.exports: $Exports<'uppy/src/locales/ru_RU'>;
}
declare module 'uppy/src/locales/tr_TR.js' {
  declare module.exports: $Exports<'uppy/src/locales/tr_TR'>;
}
declare module 'uppy/src/locales/zh_CN.js' {
  declare module.exports: $Exports<'uppy/src/locales/zh_CN'>;
}
declare module 'uppy/src/plugins/AwsS3/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/AwsS3/index'>;
}
declare module 'uppy/src/plugins/Dashboard/ActionBrowseTagline.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dashboard/ActionBrowseTagline'>;
}
declare module 'uppy/src/plugins/Dashboard/Dashboard.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dashboard/Dashboard'>;
}
declare module 'uppy/src/plugins/Dashboard/FileCard.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dashboard/FileCard'>;
}
declare module 'uppy/src/plugins/Dashboard/FileItem.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dashboard/FileItem'>;
}
declare module 'uppy/src/plugins/Dashboard/FileItemProgress.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dashboard/FileItemProgress'>;
}
declare module 'uppy/src/plugins/Dashboard/FileList.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dashboard/FileList'>;
}
declare module 'uppy/src/plugins/Dashboard/getFileTypeIcon.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dashboard/getFileTypeIcon'>;
}
declare module 'uppy/src/plugins/Dashboard/icons.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dashboard/icons'>;
}
declare module 'uppy/src/plugins/Dashboard/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dashboard/index'>;
}
declare module 'uppy/src/plugins/Dashboard/Tabs.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dashboard/Tabs'>;
}
declare module 'uppy/src/plugins/Dashboard/UploadBtn.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dashboard/UploadBtn'>;
}
declare module 'uppy/src/plugins/DragDrop/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/DragDrop/index'>;
}
declare module 'uppy/src/plugins/Dropbox/icons.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dropbox/icons'>;
}
declare module 'uppy/src/plugins/Dropbox/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dropbox/index'>;
}
declare module 'uppy/src/plugins/Dummy.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dummy'>;
}
declare module 'uppy/src/plugins/FileInput.js' {
  declare module.exports: $Exports<'uppy/src/plugins/FileInput'>;
}
declare module 'uppy/src/plugins/GoldenRetriever/cleanup.js' {
  declare module.exports: $Exports<'uppy/src/plugins/GoldenRetriever/cleanup'>;
}
declare module 'uppy/src/plugins/GoldenRetriever/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/GoldenRetriever/index'>;
}
declare module 'uppy/src/plugins/GoldenRetriever/IndexedDBStore.js' {
  declare module.exports: $Exports<'uppy/src/plugins/GoldenRetriever/IndexedDBStore'>;
}
declare module 'uppy/src/plugins/GoldenRetriever/MetaDataStore.js' {
  declare module.exports: $Exports<'uppy/src/plugins/GoldenRetriever/MetaDataStore'>;
}
declare module 'uppy/src/plugins/GoldenRetriever/ServiceWorker.js' {
  declare module.exports: $Exports<'uppy/src/plugins/GoldenRetriever/ServiceWorker'>;
}
declare module 'uppy/src/plugins/GoldenRetriever/ServiceWorkerStore.js' {
  declare module.exports: $Exports<'uppy/src/plugins/GoldenRetriever/ServiceWorkerStore'>;
}
declare module 'uppy/src/plugins/GoogleDrive/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/GoogleDrive/index'>;
}
declare module 'uppy/src/plugins/Informer.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Informer'>;
}
declare module 'uppy/src/plugins/Instagram/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Instagram/index'>;
}
declare module 'uppy/src/plugins/MagicLog.js' {
  declare module.exports: $Exports<'uppy/src/plugins/MagicLog'>;
}
declare module 'uppy/src/plugins/MetaData.js' {
  declare module.exports: $Exports<'uppy/src/plugins/MetaData'>;
}
declare module 'uppy/src/plugins/Plugin.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Plugin'>;
}
declare module 'uppy/src/plugins/Plugin.test.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Plugin.test'>;
}
declare module 'uppy/src/plugins/ProgressBar.js' {
  declare module.exports: $Exports<'uppy/src/plugins/ProgressBar'>;
}
declare module 'uppy/src/plugins/Redux.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Redux'>;
}
declare module 'uppy/src/plugins/Redux.test.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Redux.test'>;
}
declare module 'uppy/src/plugins/ReduxDevTools.js' {
  declare module.exports: $Exports<'uppy/src/plugins/ReduxDevTools'>;
}
declare module 'uppy/src/plugins/RestoreFiles/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/RestoreFiles/index'>;
}
declare module 'uppy/src/plugins/StatusBar/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/StatusBar/index'>;
}
declare module 'uppy/src/plugins/StatusBar/StatusBar.js' {
  declare module.exports: $Exports<'uppy/src/plugins/StatusBar/StatusBar'>;
}
declare module 'uppy/src/plugins/Transloadit/Client.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Transloadit/Client'>;
}
declare module 'uppy/src/plugins/Transloadit/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Transloadit/index'>;
}
declare module 'uppy/src/plugins/Transloadit/index.test.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Transloadit/index.test'>;
}
declare module 'uppy/src/plugins/Transloadit/Socket.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Transloadit/Socket'>;
}
declare module 'uppy/src/plugins/Tus.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Tus'>;
}
declare module 'uppy/src/plugins/Tus10.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Tus10'>;
}
declare module 'uppy/src/plugins/Webcam/CameraIcon.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/CameraIcon'>;
}
declare module 'uppy/src/plugins/Webcam/CameraScreen.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/CameraScreen'>;
}
declare module 'uppy/src/plugins/Webcam/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/index'>;
}
declare module 'uppy/src/plugins/Webcam/PermissionsScreen.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/PermissionsScreen'>;
}
declare module 'uppy/src/plugins/Webcam/RecordButton.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/RecordButton'>;
}
declare module 'uppy/src/plugins/Webcam/RecordStartIcon.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/RecordStartIcon'>;
}
declare module 'uppy/src/plugins/Webcam/RecordStopIcon.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/RecordStopIcon'>;
}
declare module 'uppy/src/plugins/Webcam/SnapshotButton.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/SnapshotButton'>;
}
declare module 'uppy/src/plugins/Webcam/supportsMediaRecorder.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/supportsMediaRecorder'>;
}
declare module 'uppy/src/plugins/Webcam/supportsMediaRecorder.test.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/supportsMediaRecorder.test'>;
}
declare module 'uppy/src/plugins/Webcam/WebcamIcon.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/WebcamIcon'>;
}
declare module 'uppy/src/plugins/XHRUpload.js' {
  declare module.exports: $Exports<'uppy/src/plugins/XHRUpload'>;
}
declare module 'uppy/src/Provider.js' {
  declare module.exports: $Exports<'uppy/src/Provider'>;
}
declare module 'uppy/src/react/Dashboard.js' {
  declare module.exports: $Exports<'uppy/src/react/Dashboard'>;
}
declare module 'uppy/src/react/DashboardModal.js' {
  declare module.exports: $Exports<'uppy/src/react/DashboardModal'>;
}
declare module 'uppy/src/react/DragDrop.js' {
  declare module.exports: $Exports<'uppy/src/react/DragDrop'>;
}
declare module 'uppy/src/react/index.js' {
  declare module.exports: $Exports<'uppy/src/react/index'>;
}
declare module 'uppy/src/react/ProgressBar.js' {
  declare module.exports: $Exports<'uppy/src/react/ProgressBar'>;
}
declare module 'uppy/src/react/StatusBar.js' {
  declare module.exports: $Exports<'uppy/src/react/StatusBar'>;
}
declare module 'uppy/src/react/Wrapper.js' {
  declare module.exports: $Exports<'uppy/src/react/Wrapper'>;
}
declare module 'uppy/src/store/DefaultStore.js' {
  declare module.exports: $Exports<'uppy/src/store/DefaultStore'>;
}
declare module 'uppy/src/store/DefaultStore.test.js' {
  declare module.exports: $Exports<'uppy/src/store/DefaultStore.test'>;
}
declare module 'uppy/src/store/ReduxStore.js' {
  declare module.exports: $Exports<'uppy/src/store/ReduxStore'>;
}
declare module 'uppy/src/store/ReduxStore.test.js' {
  declare module.exports: $Exports<'uppy/src/store/ReduxStore.test'>;
}
declare module 'uppy/src/vendor/file-type/index.js' {
  declare module.exports: $Exports<'uppy/src/vendor/file-type/index'>;
}
declare module 'uppy/test/acceptance/dragdrop.spec.js' {
  declare module.exports: $Exports<'uppy/test/acceptance/dragdrop.spec'>;
}
declare module 'uppy/test/acceptance/dummy.spec.js' {
  declare module.exports: $Exports<'uppy/test/acceptance/dummy.spec'>;
}
declare module 'uppy/test/acceptance/fallback.spec.js' {
  declare module.exports: $Exports<'uppy/test/acceptance/fallback.spec'>;
}
declare module 'uppy/test/acceptance/i18n.spec.js' {
  declare module.exports: $Exports<'uppy/test/acceptance/i18n.spec'>;
}
declare module 'uppy/test/acceptance/index.js' {
  declare module.exports: $Exports<'uppy/test/acceptance/index'>;
}
declare module 'uppy/test/acceptance/multipart.spec.js' {
  declare module.exports: $Exports<'uppy/test/acceptance/multipart.spec'>;
}
declare module 'uppy/test/acceptance/saucelabs-dummy.spec.js' {
  declare module.exports: $Exports<'uppy/test/acceptance/saucelabs-dummy.spec'>;
}
declare module 'uppy/test/acceptance/tools.js' {
  declare module.exports: $Exports<'uppy/test/acceptance/tools'>;
}
declare module 'uppy/test/endtoend/dist/bundle.js' {
  declare module.exports: $Exports<'uppy/test/endtoend/dist/bundle'>;
}
declare module 'uppy/test/endtoend/specs/uppy.test.js' {
  declare module.exports: $Exports<'uppy/test/endtoend/specs/uppy.test'>;
}
declare module 'uppy/test/endtoend/src/main.js' {
  declare module.exports: $Exports<'uppy/test/endtoend/src/main'>;
}
declare module 'uppy/test/endtoend/wdio.local.conf.js' {
  declare module.exports: $Exports<'uppy/test/endtoend/wdio.local.conf'>;
}
declare module 'uppy/test/endtoend/wdio.remote.conf.js' {
  declare module.exports: $Exports<'uppy/test/endtoend/wdio.remote.conf'>;
}
declare module 'uppy/test/mocks/acquirerPlugin1.js' {
  declare module.exports: $Exports<'uppy/test/mocks/acquirerPlugin1'>;
}
declare module 'uppy/test/mocks/acquirerPlugin2.js' {
  declare module.exports: $Exports<'uppy/test/mocks/acquirerPlugin2'>;
}
declare module 'uppy/test/mocks/invalidPlugin.js' {
  declare module.exports: $Exports<'uppy/test/mocks/invalidPlugin'>;
}
declare module 'uppy/test/mocks/invalidPluginWithoutId.js' {
  declare module.exports: $Exports<'uppy/test/mocks/invalidPluginWithoutId'>;
}
declare module 'uppy/test/mocks/invalidPluginWithoutType.js' {
  declare module.exports: $Exports<'uppy/test/mocks/invalidPluginWithoutType'>;
}
