// flow-typed signature: 7e5813144de247fa35125105c4b2298f
// flow-typed version: <<STUB>>/video-react_v0.9.4/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'video-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'video-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'video-react/dist/index.es' {
  declare module.exports: any;
}

declare module 'video-react/dist/index' {
  declare module.exports: any;
}

declare module 'video-react/dist/video-react' {
  declare module.exports: any;
}

declare module 'video-react/dist/video-react.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'video-react/dist/index.es.js' {
  declare module.exports: $Exports<'video-react/dist/index.es'>;
}
declare module 'video-react/dist/index.js' {
  declare module.exports: $Exports<'video-react/dist/index'>;
}
declare module 'video-react/dist/video-react.js' {
  declare module.exports: $Exports<'video-react/dist/video-react'>;
}
declare module 'video-react/dist/video-react.min.js' {
  declare module.exports: $Exports<'video-react/dist/video-react.min'>;
}
