const express = ('express')
const graphQLHTTP = ('express-graphql')
const bodyParser = ('body-parser')
const jwt = ('jsonwebtoken')
const passport = ('passport')
const morgan = ('morgan')
const models = ('./models')
const schema =('./schema')
const config = ('./config')
const passportConfig = ('./services/auth')
const webpackMiddleware = ('webpack-dev-middleware')
const webpack = ('webpack')
const webpackConfig = ('../webpack.config.js')
const app = express()
const router = express.Router()

app.set('port', (process.env.PORT || 5000))
app.set('is_dev', (app.settings.env === 'development'))
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: false }))
app.use(morgan('dev'))
app.use(passport.initialize())
app.use(express.static(__dirname + '/dist'))
app.use('/graphql', graphQLHTTP({ schema, graphiql: true }))
app.use(webpackMiddleware(webpack(webpackConfig)))

app.get('*', (req, res) => {
  res.sendfile('./dist/index.html')
})

module.exports = app
